"use client"; // 第69天：声明知识治理浏览器需要 React 状态、事件处理和浏览器请求能力。
import Link from "next/link"; // 第69天：引入 Next.js Link 组件提供返回聊天主页的客户端导航。
import { useCallback, useEffect, useMemo, useState } from "react"; // 第69天：引入治理台加载、标签、表单和派生数据所需 React Hooks。
import { ApiClientError, readApiData } from "@/lib/api/api-client"; // 第69天：引入统一 API 响应解析和客户端错误类型。
import type { KnowledgeScope, ProductionKnowledgePlatformSnapshot, RetrievalStrategy } from "@/lib/knowledge/production-knowledge-types"; // 第69天：引入治理快照、知识作用域和检索策略类型。
type GovernanceTab = "bases" | "documents" | "jobs" | "retrieval" | "governance"; // 第69天：定义知识治理浏览器第二版五个任务标签页。
const TABS: Array<{ id: GovernanceTab; label: string }> = [{ id: "bases", label: "Knowledge Bases（知识库）" }, { id: "documents", label: "Documents（文档）" }, { id: "jobs", label: "Index Jobs（索引任务）" }, { id: "retrieval", label: "Retrieval Debug（检索调试）" }, { id: "governance", label: "Governance（治理）" }]; // 第69天：定义任务清单要求的五标签治理导航。
const SCOPE_LABELS: Record<KnowledgeScope, string> = { user: "用户私有", workspace: "工作空间", team: "团队共享", global: "全局公开" }; // 第69天：定义知识作用域中文展示名称。
function formatTime(value?: number): string { return value ? new Date(value).toLocaleString("zh-CN", { hour12: false }) : "—"; } // 第69天：把可选时间戳格式化为中文二十四小时制文本。
function percent(value: number): string { return `${(value * 100).toFixed(1)}%`; } // 第69天：把零到一的指标格式化为百分比文本。
function statusClass(status: string): string { return ["active", "ready", "success"].includes(status) ? "bg-emerald-300/15 text-emerald-200" : ["queued", "uploaded", "updating", "indexing", "running", "building"].includes(status) ? "bg-amber-300/15 text-amber-100" : ["failed", "deleting", "deleted"].includes(status) ? "bg-rose-300/15 text-rose-100" : "bg-slate-300/10 text-slate-300"; } // 第69天：根据资源生命周期状态返回治理台颜色样式。
export function KnowledgeGovernanceExplorerV2() { // 第69天：定义 Production Knowledge & RAG Platform V1 主治理页面组件。
  const [snapshot, setSnapshot] = useState<ProductionKnowledgePlatformSnapshot | null>(null); // 第69天：保存生产知识平台完整治理快照。
  const [activeTab, setActiveTab] = useState<GovernanceTab>("bases"); // 第69天：保存当前选中的治理标签页。
  const [loading, setLoading] = useState(true); // 第69天：保存首次加载和治理动作进行状态。
  const [error, setError] = useState(""); // 第69天：保存用户可读错误信息。
  const [baseName, setBaseName] = useState("Day69 新工作空间知识库"); // 第69天：保存创建知识库表单名称。
  const [baseScope, setBaseScope] = useState<KnowledgeScope>("workspace"); // 第69天：保存创建知识库表单作用域。
  const [baseScopeId, setBaseScopeId] = useState("workspace-day69"); // 第69天：保存创建知识库表单作用域标识。
  const [selectedBaseId, setSelectedBaseId] = useState(""); // 第69天：保存上传文档和检索限定使用的知识库标识。
  const [documentTitle, setDocumentTitle] = useState("第69天增量索引说明"); // 第69天：保存上传文档表单标题。
  const [documentContent, setDocumentContent] = useState("文档上传后进入 Redis Queue，由 Indexer Worker 获取分布式锁并构建新索引版本；发布完成前旧活动版本保持可检索。标准引用必须包含文档、片段和活动索引版本。"); // 第69天：保存上传文档表单正文。
  const [query, setQuery] = useState("文档更新时为什么要保留旧活动索引？"); // 第69天：保存生产检索调试问题。
  const [strategy, setStrategy] = useState<RetrievalStrategy>("quality"); // 第69天：保存快速、平衡或质量检索策略。
  const [userId, setUserId] = useState("user-a"); // 第69天：保存检索权限上下文中的用户标识。
  const [workspaceId, setWorkspaceId] = useState("workspace-day69"); // 第69天：保存检索权限上下文中的工作空间标识。
  const loadSnapshot = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/production-knowledge", { cache: "no-store" }); setSnapshot(await readApiData<ProductionKnowledgePlatformSnapshot>(response)); } catch (caught) { setError(caught instanceof ApiClientError ? caught.message : "加载第69天生产知识平台失败"); } finally { setLoading(false); } }, []); // 第69天：读取生产知识治理快照并统一处理加载状态和错误。
  const requestAction = useCallback(async (method: "POST" | "PATCH", body: Record<string, unknown>) => { setLoading(true); setError(""); try { const response = await fetch("/api/production-knowledge", { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); setSnapshot(await readApiData<ProductionKnowledgePlatformSnapshot>(response)); } catch (caught) { setError(caught instanceof ApiClientError ? caught.message : "第69天知识治理操作失败"); } finally { setLoading(false); } }, []); // 第69天：发送创建、索引、检索与治理动作并刷新完整快照。
  useEffect(() => { const timer = window.setTimeout(() => void loadSnapshot(), 0); return () => window.clearTimeout(timer); }, [loadSnapshot]); // 第69天：组件挂载后异步加载治理快照并在卸载时清理定时器。
  const effectiveBaseId = selectedBaseId || snapshot?.knowledgeBases.find((item) => item.status === "active")?.id || ""; // 第69天：派生表单使用的知识库标识并避免在 Effect 中同步更新状态。
  const selectedBase = useMemo(() => snapshot?.knowledgeBases.find((item) => item.id === effectiveBaseId), [effectiveBaseId, snapshot]); // 第69天：派生当前选中的知识库详情。
  const metricCards = snapshot ? [{ label: "Knowledge Bases（知识库）", value: snapshot.metrics.knowledgeBaseCount }, { label: "Ready Documents（就绪文档）", value: snapshot.metrics.readyDocumentCount }, { label: "Active Chunks（活动片段）", value: snapshot.metrics.totalChunkCount }, { label: "Active Vectors（活动向量）", value: snapshot.metrics.totalVectorCount }, { label: "Retrieval Hit Rate（检索命中率）", value: percent(snapshot.metrics.retrievalHitRate) }, { label: "Citation Coverage（引用覆盖率）", value: percent(snapshot.metrics.citationCoverageRate) }, { label: "Permission Denied（权限拒绝）", value: snapshot.metrics.permissionDeniedCount }, { label: "Stale Index（失效索引）", value: snapshot.metrics.staleIndexCount }] : []; // 第69天：构造生产知识平台核心治理指标卡片。
  return ( // 第69天：返回知识治理浏览器第二版完整页面。
    <main className="min-h-screen bg-[#071018] text-slate-100"> {/* 第69天：定义深色生产知识控制台页面背景。 */}
      <div className="mx-auto max-w-[1700px] px-4 py-5 sm:px-6 lg:px-8"> {/* 第69天：定义响应式治理页面内容宽度和边距。 */}
        <header className="overflow-hidden rounded-3xl border border-teal-300/15 bg-gradient-to-br from-slate-900 via-slate-900 to-teal-950/70 shadow-2xl shadow-teal-950/30"> {/* 第69天：定义生产知识与 RAG 平台主题页头卡片。 */}
          <div className="flex flex-col gap-6 px-6 py-7 lg:flex-row lg:items-end lg:justify-between"> {/* 第69天：排列标题说明、状态徽标和导航入口。 */}
            <div className="max-w-5xl"> {/* 第69天：定义标题和平台说明区域。 */}
              <div className="flex items-center gap-3"><span className="rounded-xl bg-teal-300 px-3 py-1 font-mono text-sm font-black text-slate-950">DAY 70</span><span className="text-xs font-bold uppercase tracking-[0.28em] text-teal-300/80">Inherited Day69 Knowledge Platform</span></div> {/* 第70天：展示当前日编号和继承的第69天生产知识平台标签。 */}
              <h1 className="mt-4 text-3xl font-black tracking-tight sm:text-5xl">Production Knowledge &amp; RAG Platform <span className="text-teal-300">生产知识与检索增强生成平台</span></h1> {/* 第69天：展示页面主标题及中文说明。 */}
              <p className="mt-4 max-w-4xl text-sm leading-7 text-slate-300">把历史 RAG（检索增强生成）升级为可管理、可追踪、可隔离、可增量更新的知识平台，覆盖对象存储、异步索引、活动版本、权限过滤、标准引用、两阶段删除、指标和一致性治理。</p> {/* 第69天：概括生产知识平台完整生命周期能力。 */}
            </div> {/* 第69天：结束标题和平台说明区域。 */}
            <div className="flex flex-wrap items-center gap-2"><span className="rounded-full border border-teal-300/20 bg-teal-300/10 px-3 py-1.5 text-xs text-teal-100">{snapshot?.queueBackend ?? "Redis Queue"}</span><span className="rounded-full border border-violet-300/20 bg-violet-300/10 px-3 py-1.5 text-xs text-violet-100">Active Index Version</span><Link href="/" className="rounded-full bg-white px-4 py-1.5 text-xs font-bold text-slate-950 transition hover:bg-teal-100">返回聊天主页</Link></div> {/* 第69天：展示队列、活动版本能力和返回主页入口。 */}
          </div> {/* 第69天：结束页头主内容布局。 */}
        </header> {/* 第69天：结束生产知识平台主题页头。 */}
        {error ? <p className="mt-4 rounded-2xl border border-rose-400/30 bg-rose-400/10 px-4 py-3 text-sm text-rose-100">{error}</p> : null} {/* 第69天：按需展示接口或治理动作错误。 */}
        <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">{metricCards.map((metric) => <article key={metric.label} className="rounded-2xl border border-white/10 bg-slate-900/70 p-3"><p className="text-[11px] leading-4 text-slate-400">{metric.label}</p><p className="mt-2 font-mono text-xl font-black text-teal-200">{metric.value}</p></article>)}</div> {/* 第69天：展示知识库存、检索、引用、权限和一致性核心指标。 */}
        <nav className="mt-5 flex gap-2 overflow-x-auto rounded-2xl border border-white/10 bg-slate-900/70 p-2" role="tablist" aria-label="第69天生产知识治理标签页">{TABS.map((tab) => <button key={tab.id} type="button" role="tab" aria-selected={activeTab === tab.id} onClick={() => setActiveTab(tab.id)} className={`whitespace-nowrap rounded-xl px-4 py-2 text-sm font-bold transition ${activeTab === tab.id ? "bg-teal-300 text-slate-950" : "text-slate-400 hover:bg-white/5 hover:text-white"}`}>{tab.label}</button>)}</nav> {/* 第69天：渲染任务要求的五个可访问治理标签页。 */}
        {!snapshot ? <div className="mt-5 rounded-3xl border border-dashed border-teal-300/25 py-24 text-center text-teal-200">正在初始化 Object Storage、Redis Queue、Distributed Lock、VectorStore 与知识治理数据…</div> : null} {/* 第69天：快照未就绪时展示平台初始化占位。 */}
        {snapshot && activeTab === "bases" ? <section className="mt-5 grid gap-4 xl:grid-cols-[minmax(0,1fr)_380px]"> {/* 第69天：按需渲染知识库资产与创建表单。 */}
          <div className="grid gap-3 lg:grid-cols-2">{snapshot.knowledgeBases.map((base) => <article key={base.id} className="rounded-2xl border border-white/10 bg-slate-900/70 p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-black text-slate-100">{base.name}</h2><p className="mt-1 text-xs text-slate-400">{SCOPE_LABELS[base.scope]} · {base.scopeId}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${statusClass(base.status)}`}>{base.status}</span></div><p className="mt-3 text-sm leading-6 text-slate-300">{base.description ?? "暂无描述"}</p><div className="mt-3 grid grid-cols-2 gap-2 text-xs text-slate-400"><span>文档 {snapshot.documents.filter((item) => item.knowledgeBaseId === base.id && item.status !== "deleted").length}</span><span>Active Index V{base.activeIndexVersion ?? "—"}</span><span>{base.embeddingModelId}</span><span>{base.chunkStrategyId}</span></div><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={() => setSelectedBaseId(base.id)} className="rounded-lg border border-teal-300/25 px-2.5 py-1.5 text-[10px] font-bold text-teal-200">选择</button><button type="button" disabled={loading} onClick={() => void requestAction("PATCH", { action: "set_knowledge_base_status", knowledgeBaseId: base.id, status: base.status === "disabled" ? "active" : "disabled" })} className="rounded-lg border border-amber-300/25 px-2.5 py-1.5 text-[10px] font-bold text-amber-200 disabled:opacity-40">{base.status === "disabled" ? "Enable（启用）" : "Disable（禁用）"}</button></div></article>)}</div> {/* 第69天：展示知识库作用域、状态、文档数、活动版本和策略。 */}
          <aside className="rounded-3xl border border-teal-300/15 bg-slate-900/70 p-5"><h2 className="text-lg font-black">Create Knowledge Base（创建知识库）</h2><div className="mt-4 space-y-3"><input value={baseName} onChange={(event) => setBaseName(event.target.value)} className="w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2 text-sm" placeholder="知识库名称" /><select value={baseScope} onChange={(event) => setBaseScope(event.target.value as KnowledgeScope)} className="w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2 text-sm">{Object.entries(SCOPE_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><input value={baseScopeId} onChange={(event) => setBaseScopeId(event.target.value)} className="w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2 text-sm" placeholder="Scope ID（作用域标识）" /><button type="button" disabled={loading || !baseName.trim() || !baseScopeId.trim()} onClick={() => void requestAction("POST", { action: "create_knowledge_base", name: baseName, description: "通过第69天治理台创建的生产知识库。", scope: baseScope, scopeId: baseScopeId, createdBy: "governance-admin" })} className="w-full rounded-xl bg-teal-300 px-4 py-2 text-sm font-black text-slate-950 disabled:opacity-40">创建生产知识库</button></div></aside> {/* 第69天：提供名称、作用域和作用域标识完整创建表单。 */}
        </section> : null} {/* 第69天：结束知识库标签页条件渲染。 */}
        {snapshot && activeTab === "documents" ? <section className="mt-5 grid gap-4 xl:grid-cols-[minmax(0,1fr)_420px]"> {/* 第69天：按需渲染文档生命周期与上传表单。 */}
          <div className="space-y-3">{snapshot.documents.map((document) => <article key={document.id} className="rounded-2xl border border-white/10 bg-slate-900/70 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-black">{document.title}</h2><p className="mt-1 font-mono text-[11px] text-slate-500">{document.id}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${statusClass(document.status)}`}>{document.status}</span></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs text-slate-400 sm:grid-cols-4"><span>Document V{document.version}</span><span>Index V{document.activeIndexVersion ?? "—"}</span><span>Chunks {snapshot.manifests.find((item) => item.documentId === document.id && item.version === document.activeIndexVersion)?.chunkCount ?? 0}</span><span>{document.mimeType}</span></div><p className="mt-3 break-all rounded-xl bg-black/20 p-3 font-mono text-[11px] text-slate-500">Object：{document.storage.objectKey}</p>{document.error ? <p className="mt-3 rounded-xl bg-rose-300/10 p-3 text-xs text-rose-100">{document.error.code}：{document.error.message}</p> : null}<div className="mt-3 flex flex-wrap gap-2"><button type="button" disabled={loading || document.status === "deleted" || document.status === "deleting"} onClick={() => void requestAction("PATCH", { action: "rebuild_document", documentId: document.id })} className="rounded-lg border border-teal-300/25 px-2.5 py-1.5 text-[10px] font-bold text-teal-200 disabled:opacity-40">Rebuild（重建）</button><button type="button" disabled={loading || document.status !== "failed"} onClick={() => void requestAction("PATCH", { action: "retry_failed_index", documentId: document.id })} className="rounded-lg border border-amber-300/25 px-2.5 py-1.5 text-[10px] font-bold text-amber-200 disabled:opacity-40">Retry（重试）</button><button type="button" disabled={loading || document.status === "deleted" || document.status === "deleting"} onClick={() => void requestAction("PATCH", { action: "delete_document", documentId: document.id })} className="rounded-lg border border-rose-300/25 px-2.5 py-1.5 text-[10px] font-bold text-rose-200 disabled:opacity-40">Two-Phase Delete（两阶段删除）</button></div></article>)}</div> {/* 第69天：展示文档状态、内容版本、活动索引、片段数、对象、错误和治理动作。 */}
          <aside className="rounded-3xl border border-teal-300/15 bg-slate-900/70 p-5"><h2 className="text-lg font-black">Upload &amp; Queue（上传并排队）</h2><p className="mt-2 text-xs leading-5 text-slate-400">当前目标：{selectedBase?.name ?? "请选择知识库"}</p><div className="mt-4 space-y-3"><select value={effectiveBaseId} onChange={(event) => setSelectedBaseId(event.target.value)} className="w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2 text-sm">{snapshot.knowledgeBases.filter((item) => item.status === "active").map((base) => <option key={base.id} value={base.id}>{base.name}</option>)}</select><input value={documentTitle} onChange={(event) => setDocumentTitle(event.target.value)} className="w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2 text-sm" placeholder="Document Title（文档标题）" /><textarea value={documentContent} onChange={(event) => setDocumentContent(event.target.value)} className="h-44 w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2 text-sm leading-6" /><button type="button" disabled={loading || !effectiveBaseId || !documentTitle.trim() || !documentContent.trim()} onClick={() => void requestAction("POST", { action: "upload_document", knowledgeBaseId: effectiveBaseId, title: documentTitle, content: documentContent })} className="w-full rounded-xl bg-teal-300 px-4 py-2 text-sm font-black text-slate-950 disabled:opacity-40">上传并创建 knowledge.index Job</button></div></aside> {/* 第69天：提供对象上传、文档元数据创建和异步索引排队表单。 */}
        </section> : null} {/* 第69天：结束文档标签页条件渲染。 */}
        {snapshot && activeTab === "jobs" ? <section className="mt-5 space-y-4"> {/* 第69天：按需渲染索引任务和 Worker 控制标签页。 */}
          <div className="flex flex-wrap gap-2 rounded-2xl border border-white/10 bg-slate-900/70 p-4"><button type="button" disabled={loading} onClick={() => void requestAction("PATCH", { action: "process_next_job" })} className="rounded-xl border border-teal-300/25 px-4 py-2 text-xs font-bold text-teal-200 disabled:opacity-40">Process Next（处理下一任务）</button><button type="button" disabled={loading} onClick={() => void requestAction("PATCH", { action: "drain_jobs" })} className="rounded-xl bg-teal-300 px-4 py-2 text-xs font-black text-slate-950 disabled:opacity-40">Drain Redis Queue（清空等待队列）</button><span className="self-center text-xs text-slate-500">Backend：{snapshot.queueBackend}</span></div> {/* 第69天：提供独立 Worker 教学驱动按钮并展示队列后端。 */}
          <div className="overflow-x-auto rounded-2xl border border-white/10 bg-slate-900/70"><table className="min-w-full text-left text-xs"><thead className="border-b border-white/10 text-slate-400"><tr><th className="px-4 py-3">Job（任务）</th><th className="px-4 py-3">Status（状态）</th><th className="px-4 py-3">Idempotency Key（幂等键）</th><th className="px-4 py-3">Attempts（尝试）</th><th className="px-4 py-3">Result（结果）</th></tr></thead><tbody>{snapshot.jobs.map((job) => <tr key={job.id} className="border-b border-white/5"><td className="px-4 py-3"><p className="font-bold text-slate-200">{job.type}</p><p className="mt-1 font-mono text-[10px] text-slate-600">{job.id}</p></td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${statusClass(job.status)}`}>{job.status}</span></td><td className="px-4 py-3 font-mono text-[10px] text-slate-400">{job.idempotencyKey}</td><td className="px-4 py-3">{job.attempts}</td><td className="px-4 py-3 text-slate-400">{job.error ?? (job.result?.idempotent ? "幂等命中" : job.result?.manifestId ?? (job.result?.deleted ? "删除完成" : "—"))}</td></tr>)}</tbody></table></div> {/* 第69天：展示等待、运行、成功、失败、幂等和删除任务结果。 */}
        </section> : null} {/* 第69天：结束索引任务标签页条件渲染。 */}
        {snapshot && activeTab === "retrieval" ? <section className="mt-5 grid gap-4 xl:grid-cols-[420px_minmax(0,1fr)]"> {/* 第69天：按需渲染生产检索第二版调试标签页。 */}
          <aside className="rounded-3xl border border-teal-300/15 bg-slate-900/70 p-5"><h2 className="text-lg font-black">Production Retrieval Pipeline V2（生产检索管线第2版）</h2><div className="mt-4 space-y-3"><textarea value={query} onChange={(event) => setQuery(event.target.value)} className="h-28 w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2 text-sm leading-6" /><select value={strategy} onChange={(event) => setStrategy(event.target.value as RetrievalStrategy)} className="w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2 text-sm"><option value="fast">Fast（快速）</option><option value="balanced">Balanced（平衡）</option><option value="quality">Quality（质量）</option></select><input value={userId} onChange={(event) => setUserId(event.target.value)} className="w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2 text-sm" placeholder="User ID（用户标识）" /><input value={workspaceId} onChange={(event) => setWorkspaceId(event.target.value)} className="w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2 text-sm" placeholder="Workspace ID（工作空间标识）" /><button type="button" disabled={loading || !query.trim()} onClick={() => void requestAction("POST", { action: "retrieve", query, strategy, userId, workspaceId, topK: 5, recallK: 20, minScore: 0.08, requireCitations: true, allowGlobalKnowledge: true })} className="w-full rounded-xl bg-teal-300 px-4 py-2 text-sm font-black text-slate-950 disabled:opacity-40">执行权限过滤与活动版本检索</button></div></aside> {/* 第69天：提供查询、策略和访问上下文调试表单。 */}
          <div className="space-y-4">{snapshot.lastRetrieval ? <><article className="rounded-2xl border border-white/10 bg-slate-900/70 p-4"><h2 className="font-black">Retrieval Trace（检索轨迹）</h2><p className="mt-3 text-xs text-slate-400">Original Query：{snapshot.lastRetrieval.query}</p><p className="mt-2 text-xs text-slate-400">Rewritten Queries：{snapshot.lastRetrieval.rewrittenQueries.join(" · ")}</p><p className="mt-2 text-xs text-slate-400">Accessible Knowledge Bases：{snapshot.lastRetrieval.accessibleKnowledgeBaseIds.join(" · ") || "无"}</p><p className="mt-2 text-xs text-rose-200">Permission Filtered：{snapshot.lastRetrieval.permissionFilteredKnowledgeBaseIds.join(" · ") || "无"}</p><p className="mt-2 text-xs text-teal-200">Strategy：{snapshot.lastRetrieval.strategy} · Duration：{snapshot.lastRetrieval.durationMs}ms</p></article>{snapshot.lastRetrieval.hits.map((hit) => <article key={hit.chunkId} className="rounded-2xl border border-white/10 bg-slate-900/70 p-4"><div className="flex items-center justify-between gap-3"><h3 className="font-black text-slate-100">{hit.documentTitle}</h3><span className="font-mono text-sm font-black text-teal-200">{hit.score.toFixed(3)}</span></div><p className="mt-3 text-sm leading-6 text-slate-300">{hit.text}</p><div className="mt-3 grid grid-cols-3 gap-2 text-[11px] text-slate-500"><span>Vector {hit.vectorScore.toFixed(3)}</span><span>Keyword {hit.keywordScore.toFixed(3)}</span><span>Rerank {hit.rerankScore.toFixed(3)}</span></div><div className="mt-3 rounded-xl border border-teal-300/10 bg-teal-300/5 p-3 text-[11px] leading-5 text-teal-100"><p>Citation ID：{hit.citation.id}</p><p>Document / Chunk：{hit.citation.documentId} / {hit.citation.chunkId}</p><p>Active Index Version：V{hit.citation.indexVersion}</p><p>Location：{hit.citation.location?.section} · {hit.citation.location?.startOffset}-{hit.citation.location?.endOffset}</p></div></article>)}</> : <div className="rounded-2xl border border-dashed border-teal-300/20 py-20 text-center text-teal-200">尚无生产检索调试记录</div>}</div> {/* 第69天：展示查询改写、可访问知识库、权限过滤、评分、活动版本和标准引用。 */}
        </section> : null} {/* 第69天：结束检索调试标签页条件渲染。 */}
        {snapshot && activeTab === "governance" ? <section className="mt-5 grid gap-4 xl:grid-cols-2"> {/* 第69天：按需渲染一致性治理、事件和注册中心标签页。 */}
          <article className="rounded-3xl border border-white/10 bg-slate-900/70 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-black">Knowledge Consistency Checker（知识一致性检查器）</h2><p className="mt-1 text-xs text-slate-500">Generated：{formatTime(snapshot.consistency.generatedAt)}</p></div><div className="flex gap-2"><button type="button" disabled={loading} onClick={() => void requestAction("PATCH", { action: "scan_consistency", autoRepairSafeItems: false })} className="rounded-xl border border-teal-300/25 px-3 py-2 text-xs font-bold text-teal-200">Report Only（仅报告）</button><button type="button" disabled={loading} onClick={() => void requestAction("PATCH", { action: "scan_consistency", autoRepairSafeItems: true })} className="rounded-xl bg-teal-300 px-3 py-2 text-xs font-black text-slate-950">Auto Repair Safe Items（修复安全项）</button></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{Object.entries(snapshot.consistency).filter(([key]) => !["generatedAt", "repairedItems"].includes(key)).map(([key, value]) => <div key={key} className="rounded-xl bg-black/20 p-3"><p className="text-xs font-bold text-slate-300">{key}</p><p className="mt-2 font-mono text-xl font-black text-teal-200">{Array.isArray(value) ? value.length : 0}</p><p className="mt-1 break-all text-[10px] leading-4 text-slate-600">{Array.isArray(value) && value.length ? value.join(" · ") : "无异常"}</p></div>)}</div>{snapshot.consistency.repairedItems.length ? <p className="mt-4 rounded-xl bg-emerald-300/10 p-3 text-xs text-emerald-100">{snapshot.consistency.repairedItems.join(" · ")}</p> : null}</article> {/* 第69天：展示对象缺失、孤儿片段、孤儿向量、失效索引和安全修复结果。 */}
          <article className="rounded-3xl border border-white/10 bg-slate-900/70 p-5"><h2 className="text-lg font-black">Unified Registry（统一注册中心）</h2><ul className="mt-4 space-y-3">{snapshot.registryItems.map((item) => <li key={item.id} className="rounded-xl border border-white/10 bg-white/[0.03] p-3"><div className="flex items-center justify-between gap-3"><p className="font-bold text-slate-200">{item.name}</p><span className="rounded-full bg-teal-300/10 px-2 py-1 text-[10px] text-teal-200">{item.version}</span></div><p className="mt-2 text-xs leading-5 text-slate-500">{String(item.metadata.description ?? "")}</p></li>)}</ul></article> {/* 第69天：展示服务、切块、检索、向量、解析器和引用格式化器注册项。 */}
          <article className="rounded-3xl border border-white/10 bg-slate-900/70 p-5 xl:col-span-2"><h2 className="text-lg font-black">EventBus &amp; Trace（事件总线与链路追踪）</h2><div className="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{snapshot.events.slice().reverse().slice(0, 18).map((event) => <div key={event.id} className="rounded-xl bg-black/20 p-3"><div className="flex items-center justify-between gap-2"><p className="text-xs font-bold text-teal-100">{event.type}</p><span className="text-[10px] text-slate-600">{formatTime(event.timestamp)}</span></div><p className="mt-2 break-all font-mono text-[10px] text-slate-500">{event.traceId}</p></div>)}</div></article> {/* 第69天：展示上传、排队、索引、发布、检索、权限和删除事件审计链。 */}
        </section> : null} {/* 第69天：结束治理标签页条件渲染。 */}
      </div> {/* 第69天：结束响应式治理页面内容容器。 */}
    </main> // 第69天：结束深色生产知识控制台页面。
  ); // 第69天：结束知识治理浏览器返回。
} // 第69天：结束 KnowledgeGovernanceExplorerV2 组件。
