"use client"; // 第72天：声明可观测仪表盘需要标签页、筛选、链路查询和告警恢复交互能力。
import Link from "next/link"; // 第72天：引入Next.js Link实现返回主工作台的客户端导航。
import { useCallback, useEffect, useMemo, useState } from "react"; // 第72天：引入快照加载、派生过滤、标签页和链路选择所需Hooks。
import { readApiData } from "@/lib/api/api-client"; // 第72天：引入统一API响应解析函数。
import type { AlertSeverity, MetricAggregate, ObservabilitySnapshot, TraceQueryResult, TraceTreeNode } from "@/lib/observability/types"; // 第72天：引入仪表盘快照、指标、链路树和告警严重度类型。

type DashboardTab = "overview" | "traces" | "metrics" | "alerts" | "logs"; // 第72天：定义总览、链路、指标、告警和日志错误五个标签页。
type MetricSourceFilter = "all" | "agent" | "model" | "workflow" | "retrieval" | "memory"; // 第72天：定义Metrics Explorer要求的模块筛选值。
const TABS: { id: DashboardTab; label: string; description: string }[] = [{ id: "overview", label: "Day72 Overview（总览）", description: "Requests、Success、Latency、Cost与Errors" }, { id: "traces", label: "Day72 Trace Explorer（链路）", description: "Trace Tree、Span Timeline、Duration与Error" }, { id: "metrics", label: "Day72 Metrics Explorer（指标）", description: "Agent、Model、Workflow、RAG与Memory" }, { id: "alerts", label: "Day72 Alert Center（告警）", description: "Active、History、Severity与关联Trace" }, { id: "logs", label: "Day72 Logs & Errors（日志错误）", description: "Structured Logging与Error Tracking" }]; // 第72天：声明五个带Day72主题和中英文说明的标签页。
const METRIC_SOURCES: { id: MetricSourceFilter; label: string }[] = [{ id: "all", label: "全部" }, { id: "agent", label: "Agent" }, { id: "model", label: "Model" }, { id: "workflow", label: "Workflow" }, { id: "retrieval", label: "RAG" }, { id: "memory", label: "Memory" }]; // 第72天：声明指标浏览器模块过滤按钮。

function formatTime(value?: number): string { return value ? new Date(value).toLocaleString("zh-CN", { hour12: false }) : "—"; } // 第72天：把毫秒时间戳格式化为中文本地时间。
function formatNumber(value: number): string { return Number.isInteger(value) ? String(value) : value.toFixed(4); } // 第72天：整数直接展示小数限制为四位。
function severityClass(severity: AlertSeverity): string { return severity === "critical" ? "border-rose-300/30 bg-rose-300/10 text-rose-100" : severity === "warning" ? "border-amber-300/30 bg-amber-300/10 text-amber-100" : "border-sky-300/30 bg-sky-300/10 text-sky-100"; } // 第72天：按严重、警告和信息告警选择颜色。
function traceStatusClass(status: string): string { return status === "failed" ? "bg-rose-300/15 text-rose-200" : status === "success" ? "bg-emerald-300/15 text-emerald-200" : "bg-sky-300/15 text-sky-200"; } // 第72天：按链路成功、失败和运行中状态选择徽标颜色。

function TraceNodeView({ node, depth = 0 }: { node: TraceTreeNode; depth?: number }) { // 第72天：定义递归展示父子跨度树和时间线信息的组件。
  return <div className="relative" style={{ marginLeft: depth * 18 }}><div className={`rounded-2xl border p-3 ${node.span.status === "failed" ? "border-rose-300/25 bg-rose-300/5" : "border-white/10 bg-white/[0.03]"}`}><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="text-[10px] font-black uppercase tracking-wider text-cyan-300">{node.span.source}</p><h3 className="mt-1 text-sm font-black text-slate-100">{node.span.name}</h3><p className="mt-1 font-mono text-[9px] text-slate-600">{node.span.spanId}</p></div><div className="text-right"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${traceStatusClass(node.span.status)}`}>{node.span.status}</span><p className="mt-2 font-mono text-xs text-cyan-200">{node.span.durationMs}ms</p></div></div>{node.span.error ? <p className="mt-2 rounded-xl bg-rose-300/10 p-2 text-xs text-rose-200">{node.span.error}</p> : null}<pre className="mt-2 overflow-auto whitespace-pre-wrap text-[9px] leading-4 text-slate-500">{JSON.stringify(node.span.attributes, null, 2)}</pre></div>{node.children.length > 0 ? <div className="mt-2 space-y-2 border-l border-cyan-300/20 pl-2">{node.children.map((child) => <TraceNodeView key={child.span.spanId} node={child} depth={depth + 1} />)}</div> : null}</div>; // 第72天：展示跨度来源、状态、耗时、错误、属性和递归子跨度。
} // 第72天：结束递归跨度树展示组件。

function MetricCard({ metric, onTrace }: { metric: MetricAggregate; onTrace: (traceId: string) => void }) { // 第72天：定义展示三类指标聚合和链路跳转的卡片组件。
  const primary = metric.kind === "counter" ? metric.sum : metric.kind === "gauge" ? metric.latest : metric.p95; // 第72天：计数器展示总和、瞬时值展示最新值、直方图展示P95。
  return <article className="rounded-3xl border border-white/10 bg-slate-950/70 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-[10px] text-cyan-300">{metric.name}</p><p className="mt-1 text-xs text-slate-500">{metric.kind.toUpperCase()} · {metric.count} samples</p></div><p className="font-mono text-2xl font-black text-cyan-100">{formatNumber(primary)}</p></div><div className="mt-4 grid grid-cols-3 gap-2 text-[10px]"><div className="rounded-xl bg-white/[0.03] p-2"><p className="text-slate-600">Average</p><p className="mt-1 font-mono text-slate-300">{formatNumber(metric.average)}</p></div><div className="rounded-xl bg-white/[0.03] p-2"><p className="text-slate-600">p50 / p95</p><p className="mt-1 font-mono text-slate-300">{formatNumber(metric.p50)} / {formatNumber(metric.p95)}</p></div><div className="rounded-xl bg-white/[0.03] p-2"><p className="text-slate-600">p99 / max</p><p className="mt-1 font-mono text-slate-300">{formatNumber(metric.p99)} / {formatNumber(metric.max)}</p></div></div><div className="mt-3 flex flex-wrap gap-2">{metric.traceIds.slice(0, 4).map((traceId) => <button key={traceId} type="button" onClick={() => onTrace(traceId)} className="max-w-full truncate rounded-full border border-cyan-300/20 px-2 py-1 font-mono text-[9px] text-cyan-200 hover:bg-cyan-300/10" title={traceId}>Metric → Trace：{traceId}</button>)}</div></article>; // 第72天：展示聚合值、平均值、百分位以及指标到链路的可点击关联。
} // 第72天：结束统一指标聚合卡片组件。

export function ObservabilityDashboard() { // 第72天：定义生产可观测总览、链路、指标、告警和日志错误仪表盘。
  const [snapshot, setSnapshot] = useState<ObservabilitySnapshot | null>(null); // 第72天：保存最近一次生产可观测平台完整快照。
  const [activeTab, setActiveTab] = useState<DashboardTab>("overview"); // 第72天：保存当前选中的Day72可观测标签页。
  const [metricSource, setMetricSource] = useState<MetricSourceFilter>("all"); // 第72天：保存指标浏览器当前模块过滤条件。
  const [traceIdInput, setTraceIdInput] = useState("trace-day72-slow-rag"); // 第72天：保存Trace查询输入并默认定位慢检索链路。
  const [traceQuery, setTraceQuery] = useState<TraceQueryResult | null>(null); // 第72天：保存按traceId查询得到的链路、跨度树、日志和指标。
  const [loading, setLoading] = useState(true); // 第72天：保存快照、链路查询和告警恢复加载状态。
  const [error, setError] = useState(""); // 第72天：保存用户可读的平台请求错误。

  const refresh = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/observability", { cache: "no-store" }); const data = await readApiData<ObservabilitySnapshot>(response); setSnapshot(data); } catch (caught) { setError(caught instanceof Error ? caught.message : "加载第72天生产可观测平台失败"); } finally { setLoading(false); } }, []); // 第72天：定义读取总览、链路、指标、告警、日志和三大平台接入证据的稳定动作。
  const selectTrace = useCallback(async (traceId: string) => { if (!traceId.trim()) return; setLoading(true); setError(""); try { const response = await fetch(`/api/observability?traceId=${encodeURIComponent(traceId.trim())}`, { cache: "no-store" }); setTraceQuery(await readApiData<TraceQueryResult>(response)); setTraceIdInput(traceId.trim()); setActiveTab("traces"); } catch (caught) { setError(caught instanceof Error ? caught.message : "查询第72天分布式链路失败"); } finally { setLoading(false); } }, []); // 第72天：定义从指标、告警或输入框跳转到完整链路根因诊断的动作。
  const resolveAlert = useCallback(async (alertId: string) => { setLoading(true); setError(""); try { const response = await fetch("/api/observability", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "resolve_alert", alertId }) }); const data = await readApiData<{ snapshot: ObservabilitySnapshot }>(response); setSnapshot(data.snapshot); } catch (caught) { setError(caught instanceof Error ? caught.message : "恢复第72天告警失败"); } finally { setLoading(false); } }, []); // 第72天：定义恢复活动告警并刷新告警中心快照的动作。
  useEffect(() => { const timer = window.setTimeout(() => void refresh(), 0); return () => window.clearTimeout(timer); }, [refresh]); // 第72天：组件挂载后异步初始化示例平台并在卸载时清理定时器。

  const metricSourceByName = useMemo(() => new Map((snapshot?.metricRecords ?? []).map((record) => [record.name, record.source])), [snapshot]); // 第72天：建立统一指标名称到平台来源模块的快速查找表。
  const filteredMetrics = useMemo(() => (snapshot?.metrics ?? []).filter((metric) => metricSource === "all" || metricSourceByName.get(metric.name) === metricSource), [metricSource, metricSourceByName, snapshot]); // 第72天：按照Agent、Model、Workflow、RAG或Memory筛选指标聚合结果。
  const activeAlerts = snapshot?.alerts.filter((alert) => alert.status === "active") ?? []; // 第72天：派生活动告警列表。
  const resolvedAlerts = snapshot?.alerts.filter((alert) => alert.status === "resolved") ?? []; // 第72天：派生已恢复告警历史列表。
  const displayedTrace = traceQuery?.trace ?? snapshot?.traces.find((trace) => trace.traceId === traceIdInput) ?? snapshot?.traces[0]; // 第72天：优先展示显式查询链路否则使用快照中匹配或第一条链路。
  const displayedTree = traceQuery?.tree ?? (displayedTrace ? snapshot?.traceTrees[displayedTrace.traceId] ?? [] : []); // 第72天：读取当前展示链路对应的跨度树。
  const displayedLogs = traceQuery?.logs ?? (displayedTrace ? snapshot?.logs.filter((log) => log.traceId === displayedTrace.traceId) ?? [] : []); // 第72天：读取当前展示链路对应的结构化日志。
  const displayedMetrics = traceQuery?.metrics ?? (displayedTrace ? snapshot?.metricRecords.filter((metric) => metric.traceId === displayedTrace.traceId) ?? [] : []); // 第72天：读取当前展示链路对应的指标明细。
  const cards = snapshot ? [{ label: "Requests（请求）", value: snapshot.overview.requests }, { label: "Success Rate（成功率）", value: `${(snapshot.overview.successRate * 100).toFixed(0)}%` }, { label: "Average Latency（平均延迟）", value: `${snapshot.overview.averageLatency}ms` }, { label: "P95 Latency", value: `${snapshot.overview.p95Latency}ms` }, { label: "Cost（成本）", value: `$${snapshot.overview.cost.toFixed(4)}` }, { label: "Errors（错误）", value: snapshot.overview.errors }, { label: "Active Alerts（活动告警）", value: snapshot.overview.activeAlerts }] : []; // 第72天：整理任务清单要求的请求、成功率、延迟、成本、错误和告警总览卡片。

  return ( // 第72天：返回深色生产可观测仪表盘完整视图。
    <main className="h-full min-h-screen overflow-y-auto bg-[#050b12] text-slate-100"> {/* 第72天：定义可独立滚动的深色Observability Dashboard页面。 */}
      <div className="mx-auto w-full max-w-[1720px] p-4 sm:p-6"> {/* 第72天：定义响应式可观测页面内容容器。 */}
        <header className="rounded-3xl border border-cyan-300/15 bg-[radial-gradient(circle_at_top_left,rgba(34,211,238,0.18),transparent_34%),linear-gradient(135deg,#111827,#050b12_55%,#0c4a6e)] p-5 shadow-2xl shadow-black/30"> {/* 第72天：定义生产可观测平台渐变标题区。 */}
          <div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-center gap-4"><div className="flex size-14 flex-col items-center justify-center rounded-2xl bg-cyan-300 text-slate-950"><span className="text-[9px] font-black uppercase">Day</span><span className="font-mono text-2xl font-black">72</span></div><div><p className="text-xs font-black uppercase tracking-[0.22em] text-cyan-200">Production Upgrade V9</p><h1 className="mt-1 text-2xl font-black sm:text-3xl">Production Observability Platform</h1><p className="mt-2 text-sm text-slate-400">生产可观测平台 · Logs + Metrics + Trace → Alert + Dashboard + Diagnosis</p></div></div><div className="flex flex-wrap gap-2"><button type="button" disabled={loading} onClick={() => void refresh()} className="rounded-xl border border-cyan-300/30 px-4 py-2 text-xs font-bold text-cyan-100 transition hover:bg-cyan-300/10 disabled:opacity-50">刷新Day72快照</button><Link href="/" className="rounded-xl border border-white/10 px-4 py-2 text-xs font-bold text-slate-300 transition hover:bg-white/5">返回Day72对话工作台</Link></div></div> {/* 第72天：展示Day72徽标、生产化升级标题、可观测闭环和导航动作。 */}
          <div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">{cards.map((card) => <article key={card.label} className="rounded-2xl border border-white/10 bg-slate-950/55 p-3"><p className="text-[11px] text-slate-500">{card.label}</p><p className="mt-2 font-mono text-xl font-black text-cyan-200">{card.value}</p></article>)}</div> {/* 第72天：展示生产可观测总览七项核心指标。 */}
        </header> {/* 第72天：结束生产可观测平台标题区。 */}
        {error ? <p className="mt-4 rounded-2xl border border-rose-300/20 bg-rose-300/10 p-4 text-sm text-rose-100">{error}</p> : null} {/* 第72天：按需展示生产可观测平台请求错误。 */}
        <nav className="mt-4 grid gap-2 rounded-3xl border border-white/10 bg-slate-950/70 p-2 md:grid-cols-5" role="tablist" aria-label="Day 72 Production Observability Platform标签页">{TABS.map((tab) => <button key={tab.id} type="button" role="tab" aria-selected={activeTab === tab.id} onClick={() => setActiveTab(tab.id)} className={`rounded-2xl px-4 py-3 text-left transition ${activeTab === tab.id ? "bg-cyan-300 text-slate-950" : "text-slate-400 hover:bg-white/5 hover:text-white"}`}><span className="block text-sm font-black">{tab.label}</span><span className={`mt-1 block text-[11px] ${activeTab === tab.id ? "text-slate-700" : "text-slate-600"}`}>{tab.description}</span></button>)}</nav> {/* 第72天：渲染带Day72相关标题的五个生产可观测标签页。 */}
        {!snapshot ? <div className="mt-4 rounded-3xl border border-dashed border-cyan-300/25 py-24 text-center text-cyan-200">正在初始化Logs、Metrics、Distributed Trace V2、Error Tracking、Alert Engine与Sampling Strategy…</div> : null} {/* 第72天：快照未就绪时展示可观测能力初始化占位。 */}

        {snapshot && activeTab === "overview" ? <section className="mt-4 grid gap-4 xl:grid-cols-[1.1fr_0.9fr]"> {/* 第72天：按需渲染可观测平台总览标签页。 */}
          <div className="space-y-4"><article className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><h2 className="text-lg font-black">Unified Observability Signals（统一观测信号）</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-cyan-300/5 p-4"><p className="text-xs font-black text-cyan-300">Logs</p><p className="mt-2 font-mono text-3xl font-black">{snapshot.logs.length}</p><p className="mt-1 text-[11px] text-slate-500">结构化日志可按level、source、traceId查询</p></div><div className="rounded-2xl bg-violet-300/5 p-4"><p className="text-xs font-black text-violet-300">Metrics</p><p className="mt-2 font-mono text-3xl font-black">{snapshot.metrics.length}</p><p className="mt-1 text-[11px] text-slate-500">Counter、Gauge与Histogram统一聚合</p></div><div className="rounded-2xl bg-emerald-300/5 p-4"><p className="text-xs font-black text-emerald-300">Traces</p><p className="mt-2 font-mono text-3xl font-black">{snapshot.traces.length}</p><p className="mt-1 text-[11px] text-slate-500">错误强制采样与高价值请求保留</p></div></div><div className="mt-4 flex flex-wrap items-center gap-2 text-xs font-bold"><span className="rounded-full bg-violet-300/10 px-3 py-2 text-violet-200">Metric</span><span>→</span><span className="rounded-full bg-cyan-300/10 px-3 py-2 text-cyan-200">Trace</span><span>→</span><span className="rounded-full bg-emerald-300/10 px-3 py-2 text-emerald-200">Root Cause</span></div></article><article className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><h2 className="text-lg font-black">Recent ObservationEvent（统一观测事件）</h2><div className="mt-3 space-y-2">{snapshot.observations.slice(-10).reverse().map((event) => <div key={event.id} className="rounded-2xl border border-white/5 bg-white/[0.02] p-3"><div className="flex items-center justify-between gap-2"><span className="font-mono text-[10px] text-cyan-300">{event.type} · {event.source} · {event.level}</span><span className="text-[10px] text-slate-600">{formatTime(event.timestamp)}</span></div><p className="mt-2 break-all font-mono text-[9px] text-slate-500">{event.traceId}</p></div>)}</div></article></div> {/* 第72天：展示三类统一信号、指标链路根因闭环和最近观测事件。 */}
          <div className="space-y-4"><article className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><h2 className="font-black">RuntimeContext / EventBus / UnifiedRegistry</h2><div className="mt-3 space-y-3"><div className="rounded-2xl bg-white/[0.03] p-3"><p className="text-xs font-black text-cyan-300">observabilityContext</p><pre className="mt-2 max-h-48 overflow-auto whitespace-pre-wrap text-[9px] leading-4 text-slate-500">{JSON.stringify(snapshot.runtimeContexts[0]?.observabilityContext ?? {}, null, 2)}</pre></div><div className="rounded-2xl bg-white/[0.03] p-3"><p className="text-xs font-black text-amber-300">EventBus · {snapshot.events.length}</p><div className="mt-2 flex flex-wrap gap-1">{Array.from(new Set(snapshot.events.map((event) => event.type))).map((type) => <span key={type} className="rounded-full bg-black/20 px-2 py-1 font-mono text-[9px] text-slate-400">{type}</span>)}</div></div><div className="rounded-2xl bg-white/[0.03] p-3"><p className="text-xs font-black text-violet-300">UnifiedRegistry · {snapshot.registryItems.length}</p><ul className="mt-2 space-y-1 text-[10px] text-slate-500">{snapshot.registryItems.map((item) => <li key={item.id}>{item.name} · {item.version}</li>)}</ul></div></div></article><article className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><h2 className="font-black">Sampling Strategy（采样策略）</h2><div className="mt-3 space-y-2 text-xs text-slate-400"><p>开发请求：Full Sampling（全量采样）</p><p>普通请求：Ratio Sampling（比例采样）</p><p>错误请求：Error Forced Sampling（错误强制采样）</p><p>高成本、VIP、关键工作流、低质量：High Value Sampling（高价值采样）</p></div></article></div> {/* 第72天：展示三大平台接入证据和四类采样策略。 */}
        </section> : null} {/* 第72天：结束可观测平台总览标签页条件渲染。 */}

        {snapshot && activeTab === "traces" ? <section className="mt-4 grid gap-4 xl:grid-cols-[0.36fr_0.64fr]"> {/* 第72天：按需渲染分布式链路浏览器标签页。 */}
          <aside className="space-y-4"><article className="rounded-3xl border border-white/10 bg-slate-950/70 p-4"><label className="text-xs font-black text-cyan-200" htmlFor="day72-trace-query">Trace ID（链路标识）</label><div className="mt-2 flex gap-2"><input id="day72-trace-query" value={traceIdInput} onChange={(event) => setTraceIdInput(event.target.value)} className="min-w-0 flex-1 rounded-xl border border-white/10 bg-[#050b12] px-3 py-2 font-mono text-[10px] outline-none focus:border-cyan-300/40" /><button type="button" disabled={loading} onClick={() => void selectTrace(traceIdInput)} className="rounded-xl bg-cyan-300 px-3 py-2 text-xs font-black text-slate-950 disabled:opacity-50">查询</button></div></article><div className="space-y-2">{snapshot.traces.map((trace) => <button key={trace.traceId} type="button" onClick={() => void selectTrace(trace.traceId)} className={`w-full rounded-2xl border p-4 text-left transition ${displayedTrace?.traceId === trace.traceId ? "border-cyan-300/40 bg-cyan-300/10" : "border-white/10 bg-slate-950/70 hover:bg-white/[0.04]"}`}><div className="flex items-center justify-between gap-2"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${traceStatusClass(trace.status)}`}>{trace.status}</span><span className="font-mono text-xs text-cyan-200">{trace.durationMs}ms</span></div><h2 className="mt-3 text-sm font-black">{trace.rootOperation}</h2><p className="mt-2 break-all font-mono text-[9px] text-slate-600">{trace.traceId}</p><p className="mt-2 text-[10px] text-slate-500">{trace.spans.length} spans · {trace.samplingReason}</p></button>)}</div></aside> {/* 第72天：展示traceId查询输入和已采样链路列表。 */}
          <div className="space-y-4">{displayedTrace ? <><article className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-[10px] text-cyan-300">{displayedTrace.traceId}</p><h2 className="mt-1 text-xl font-black">{displayedTrace.rootOperation}</h2><p className="mt-2 text-xs text-slate-500">Request：{displayedTrace.requestId} · {formatTime(displayedTrace.startedAt)} · Sampling：{displayedTrace.samplingReason}</p></div><span className={`rounded-full px-3 py-2 text-xs font-black ${traceStatusClass(displayedTrace.status)}`}>{displayedTrace.status.toUpperCase()} · {displayedTrace.durationMs}ms</span></div><div className="mt-4 space-y-2">{displayedTree.map((node) => <TraceNodeView key={node.span.spanId} node={node} />)}</div></article><div className="grid gap-4 lg:grid-cols-2"><article className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><h2 className="font-black">Associated Logs（关联日志）</h2><div className="mt-3 space-y-2">{displayedLogs.map((log) => <div key={log.id} className="rounded-2xl bg-white/[0.03] p-3"><p className={`text-xs font-black ${log.level === "error" ? "text-rose-300" : log.level === "warn" ? "text-amber-300" : "text-cyan-300"}`}>{log.level.toUpperCase()} · {log.source}</p><p className="mt-2 text-xs text-slate-300">{log.message}</p></div>)}</div></article><article className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><h2 className="font-black">Associated Metrics（关联指标）</h2><div className="mt-3 space-y-2">{displayedMetrics.map((metric) => <div key={metric.id} className="flex items-center justify-between gap-3 rounded-2xl bg-white/[0.03] p-3"><div><p className="font-mono text-[10px] text-violet-300">{metric.name}</p><p className="mt-1 text-[9px] text-slate-600">{metric.kind} · {metric.source}</p></div><p className="font-mono text-sm font-black">{formatNumber(metric.value)}</p></div>)}</div></article></div></> : <div className="rounded-3xl border border-dashed border-cyan-300/25 py-24 text-center text-cyan-200">请输入有效traceId查看完整调用链。</div>}</div> {/* 第72天：展示Trace Tree、Span Timeline、Duration、Error、关联日志和关联指标。 */}
        </section> : null} {/* 第72天：结束分布式链路浏览器标签页条件渲染。 */}

        {snapshot && activeTab === "metrics" ? <section className="mt-4"> {/* 第72天：按需渲染统一指标浏览器标签页。 */}
          <div className="flex flex-wrap gap-2 rounded-3xl border border-white/10 bg-slate-950/70 p-3">{METRIC_SOURCES.map((source) => <button key={source.id} type="button" onClick={() => setMetricSource(source.id)} className={`rounded-xl px-4 py-2 text-xs font-black transition ${metricSource === source.id ? "bg-violet-300 text-slate-950" : "bg-white/[0.03] text-slate-400 hover:text-white"}`}>{source.label}</button>)}</div> {/* 第72天：展示Agent、Model、Workflow、RAG和Memory模块筛选按钮。 */}
          <div className="mt-4 grid gap-4 lg:grid-cols-2 2xl:grid-cols-3">{filteredMetrics.map((metric) => <MetricCard key={metric.name} metric={metric} onTrace={(traceId) => void selectTrace(traceId)} />)}</div> {/* 第72天：展示计数器、瞬时值、直方图百分位以及Metric到Trace跳转。 */}
        </section> : null} {/* 第72天：结束统一指标浏览器标签页条件渲染。 */}

        {snapshot && activeTab === "alerts" ? <section className="mt-4 grid gap-4 xl:grid-cols-2"> {/* 第72天：按需渲染活动告警和历史告警中心标签页。 */}
          <article className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><h2 className="text-lg font-black text-rose-200">Active Alerts（活动告警） · {activeAlerts.length}</h2><div className="mt-4 space-y-3">{activeAlerts.map((alert) => <div key={alert.id} className={`rounded-2xl border p-4 ${severityClass(alert.severity)}`}><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-wider">{alert.severity}</p><h3 className="mt-1 font-black">{alert.title}</h3></div><button type="button" disabled={loading} onClick={() => void resolveAlert(alert.id)} className="rounded-xl border border-current/20 px-3 py-2 text-[10px] font-black disabled:opacity-50">Resolve（恢复）</button></div><p className="mt-3 text-xs leading-5 opacity-80">{alert.message}</p><p className="mt-2 font-mono text-[10px] opacity-70">actual {alert.actualValue} / threshold {alert.threshold}</p><div className="mt-3 flex flex-wrap gap-2">{alert.traceIds.map((traceId) => <button key={traceId} type="button" onClick={() => void selectTrace(traceId)} className="rounded-full border border-current/20 px-2 py-1 font-mono text-[9px]">Alert → Trace：{traceId}</button>)}</div></div>)}</div></article> {/* 第72天：展示活动告警严重度、真实值、阈值、恢复动作和关联链路。 */}
          <div className="space-y-4"><article className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><h2 className="text-lg font-black">Alert Rules（告警规则） · {snapshot.alertRules.length}</h2><div className="mt-4 space-y-2">{snapshot.alertRules.map((rule) => <div key={rule.id} className="rounded-2xl bg-white/[0.03] p-3"><div className="flex items-center justify-between gap-2"><p className="text-xs font-black text-slate-200">{rule.name}</p><span className={`rounded-full px-2 py-1 text-[9px] font-black ${severityClass(rule.severity)}`}>{rule.severity}</span></div><p className="mt-2 font-mono text-[10px] text-cyan-300">{rule.target} · {rule.aggregation} {rule.operator} {rule.threshold}</p><p className="mt-1 text-[10px] text-slate-600">Signal：{rule.signal} · Window：{rule.windowMs}ms</p></div>)}</div></article><article className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><h2 className="text-lg font-black">Alert History（告警历史） · {resolvedAlerts.length}</h2><div className="mt-3 space-y-2">{resolvedAlerts.map((alert) => <div key={alert.id} className="rounded-2xl bg-emerald-300/5 p-3"><p className="text-xs font-black text-emerald-200">{alert.title}</p><p className="mt-1 text-[10px] text-slate-500">Triggered：{formatTime(alert.triggeredAt)} · Resolved：{formatTime(alert.resolvedAt)}</p></div>)}</div></article></div> {/* 第72天：展示告警规则、信号来源、时间窗口和已恢复历史。 */}
        </section> : null} {/* 第72天：结束活动告警和历史告警中心标签页条件渲染。 */}

        {snapshot && activeTab === "logs" ? <section className="mt-4 grid gap-4 xl:grid-cols-[1.1fr_0.9fr]"> {/* 第72天：按需渲染结构化日志和错误追踪标签页。 */}
          <article className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><h2 className="text-lg font-black">Structured Logging（结构化日志） · {snapshot.logs.length}</h2><div className="mt-4 space-y-3">{snapshot.logs.slice().reverse().map((log) => <div key={log.id} className={`rounded-2xl border p-4 ${log.level === "error" ? "border-rose-300/20 bg-rose-300/5" : log.level === "warn" ? "border-amber-300/20 bg-amber-300/5" : "border-white/10 bg-white/[0.02]"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className={`text-xs font-black ${log.level === "error" ? "text-rose-300" : log.level === "warn" ? "text-amber-300" : "text-cyan-300"}`}>{log.level.toUpperCase()} · {log.source}</p><p className="mt-2 text-sm text-slate-200">{log.message}</p></div><span className="text-[10px] text-slate-600">{formatTime(log.createdAt)}</span></div><button type="button" onClick={() => log.traceId && void selectTrace(log.traceId)} className="mt-3 break-all text-left font-mono text-[9px] text-cyan-300">traceId：{log.traceId ?? "—"}</button><pre className="mt-3 overflow-auto whitespace-pre-wrap rounded-xl bg-black/20 p-3 text-[9px] leading-4 text-slate-500">{JSON.stringify(log.metadata, null, 2)}</pre></div>)}</div></article> {/* 第72天：展示可按level、source、traceId、model和metadata查询的结构化日志。 */}
          <article className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><h2 className="text-lg font-black">Error Tracking（错误追踪） · {snapshot.errors.length}</h2><div className="mt-4 space-y-3">{snapshot.errors.map((item) => <div key={item.id} className="rounded-2xl border border-rose-300/20 bg-rose-300/5 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-[10px] text-rose-300">{item.errorType}</p><h3 className="mt-1 text-sm font-black">{item.message}</h3></div><span className="rounded-full bg-rose-300/15 px-3 py-1 font-mono text-sm font-black text-rose-200">× {item.count}</span></div><div className="mt-3 grid grid-cols-2 gap-2 text-[10px] text-slate-500"><p>Source：{item.source}</p><p>Model：{item.model ?? "—"}</p><p>First：{formatTime(item.firstSeenAt)}</p><p>Last：{formatTime(item.lastSeenAt)}</p></div><div className="mt-3 flex flex-wrap gap-2">{item.traceIds.map((traceId) => <button key={traceId} type="button" onClick={() => void selectTrace(traceId)} className="rounded-full border border-rose-300/20 px-2 py-1 font-mono text-[9px] text-rose-200">Error → Trace：{traceId}</button>)}</div></div>)}</div></article> {/* 第72天：展示错误类型排行、来源、模型、次数、增长时间和关联链路。 */}
        </section> : null} {/* 第72天：结束结构化日志和错误追踪标签页条件渲染。 */}
      </div> {/* 第72天：结束响应式生产可观测页面内容容器。 */}
    </main> // 第72天：结束深色生产可观测仪表盘页面。
  ); // 第72天：结束ObservabilityDashboard视图返回。
} // 第72天：结束生产可观测仪表盘组件。
