"use client"; // 第70天：声明 Workflow Explorer V2 需要状态、生命周期和按钮交互能力。
import { useCallback, useEffect, useMemo, useState } from "react"; // 第70天：引入快照加载、派生数据与标签页交互所需 Hooks。
import Link from "next/link"; // 第70天：引入 Next.js Link 实现返回主工作台的客户端导航。
import { readApiData } from "@/lib/api/api-client"; // 第70天：引入统一 API 响应解析函数。
import type { DurableWorkflowPlatformSnapshot, WorkflowExecutionStatusV2 } from "@/lib/workflow/durable-workflow-types"; // 第70天：引入平台快照与执行状态类型。
type ExplorerTab = "catalog" | "executions" | "replay"; // 第70天：定义任务要求的三个 Workflow Explorer V2 标签页。
const TABS: { id: ExplorerTab; label: string; description: string }[] = [{ id: "catalog", label: "Day71 Workflow Catalog（工作流目录）", description: "评估平台关联的版本、状态、负责人和冻结步骤" }, { id: "executions", label: "Day71 Execution Explorer（执行浏览器）", description: "评估平台关联的状态、当前步骤、检查点和恢复动作" }, { id: "replay", label: "Day71 Replay Debug（回放调试）", description: "评估平台关联的事件时间线、输出与恢复点" }]; // 第71天：更新三个继承工作流标签页的 Day71 相关标题与说明。
function formatTime(value?: number): string { return value ? new Date(value).toLocaleString("zh-CN", { hour12: false }) : "—"; } // 第70天：把毫秒时间戳格式化为中文本地时间。
function statusClass(status: WorkflowExecutionStatusV2 | string): string { if (["completed", "active"].includes(status)) return "bg-emerald-300/15 text-emerald-200"; if (["failed", "cancelled", "deprecated"].includes(status)) return "bg-rose-300/15 text-rose-200"; if (["waiting", "paused", "testing"].includes(status)) return "bg-amber-300/15 text-amber-200"; return "bg-sky-300/15 text-sky-200"; } // 第70天：按执行与定义状态选择治理台徽标颜色。
export function WorkflowExplorerV2() { // 第70天：定义持久化工作流目录、执行和回放治理浏览器。
  const [snapshot, setSnapshot] = useState<DurableWorkflowPlatformSnapshot | null>(null); // 第70天：保存最近一次持久化工作流平台快照。
  const [activeTab, setActiveTab] = useState<ExplorerTab>("catalog"); // 第70天：保存当前选中的第70天治理标签页。
  const [loading, setLoading] = useState(true); // 第70天：保存快照请求和治理动作加载状态。
  const [error, setError] = useState(""); // 第70天：保存用户可读的平台请求错误。
  const [query, setQuery] = useState("如何让 Agent 长期可靠执行复杂任务？"); // 第70天：保存新执行使用的研究查询输入。
  const [version, setVersion] = useState(2); // 第70天：保存启动执行时选择的冻结工作流版本。
  const refresh = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/durable-workflows", { cache: "no-store" }); setSnapshot(await readApiData<DurableWorkflowPlatformSnapshot>(response)); } catch (caught) { setError(caught instanceof Error ? caught.message : "加载持久化工作流平台失败"); } finally { setLoading(false); } }, []); // 第70天：定义读取定义、执行、检查点、事件、上下文、注册与指标快照的稳定动作。
  useEffect(() => { const timer = window.setTimeout(() => void refresh(), 0); return () => window.clearTimeout(timer); }, [refresh]); // 第70天：组件挂载后异步加载示例平台并在卸载时清理定时器。
  const requestAction = useCallback(async (method: "POST" | "PATCH", body: Record<string, unknown>) => { setLoading(true); setError(""); try { const response = await fetch("/api/durable-workflows", { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); setSnapshot(await readApiData<DurableWorkflowPlatformSnapshot>(response)); } catch (caught) { setError(caught instanceof Error ? caught.message : "执行第71天评估关联工作流动作失败"); } finally { setLoading(false); } }, []); // 第71天：定义启动、恢复、确认、回放与取消共用的继承工作流 API 动作。
  const stateByExecution = useMemo(() => new Map((snapshot?.states ?? []).map((state) => [state.executionId, state])), [snapshot]); // 第70天：建立执行标识到 Workflow State V2 的快速查找表。
  const definitionByExecution = useMemo(() => new Map((snapshot?.definitions ?? []).map((definition) => [`${definition.id}@${definition.version}`, definition])), [snapshot]); // 第70天：建立执行冻结版本到 Workflow Definition V2 的快速查找表。
  const metrics = snapshot?.metrics; // 第70天：读取工作流指标第二版供顶部卡片展示。
  const metricCards = [{ label: "执行总数", value: metrics?.totalExecutions ?? 0 }, { label: "成功率", value: `${((metrics?.successRate ?? 0) * 100).toFixed(0)}%` }, { label: "失败率", value: `${((metrics?.failureRate ?? 0) * 100).toFixed(0)}%` }, { label: "平均时长", value: `${metrics?.averageDuration ?? 0}ms` }, { label: "Retry", value: metrics?.retryCount ?? 0 }, { label: "Resume", value: metrics?.resumeCount ?? 0 }, { label: "Replay", value: metrics?.replayCount ?? 0 }, { label: "Checkpoint", value: metrics?.checkpointCount ?? 0 }, { label: "活动执行", value: metrics?.activeExecutions ?? 0 }]; // 第70天：整理任务清单要求的九项工作流指标卡片。
  return ( // 第70天：返回深色持久化工作流治理台完整视图。
    <main className="h-full min-h-screen overflow-y-auto bg-[#07111f] text-slate-100"> {/* 第70天：定义可独立滚动的深色 Workflow Explorer V2 页面。 */}
      <div className="mx-auto w-full max-w-[1600px] p-4 sm:p-6"> {/* 第70天：定义响应式治理页面内容容器。 */}
        <header className="rounded-3xl border border-violet-300/15 bg-gradient-to-br from-violet-400/15 via-slate-950 to-cyan-400/10 p-5 shadow-2xl shadow-black/30"> {/* 第70天：定义持久化工作流平台标题区。 */}
          <div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-center gap-4"><div className="flex size-14 flex-col items-center justify-center rounded-2xl bg-violet-300 text-slate-950"><span className="text-[9px] font-black uppercase">Day</span><span className="font-mono text-2xl font-black">71</span></div><div><p className="text-xs font-black uppercase tracking-[0.22em] text-violet-200">Production Upgrade V8 · Inherited Day70 Workflow</p><h1 className="mt-1 text-2xl font-black sm:text-3xl">Durable Agent Workflow Platform V1</h1><p className="mt-2 text-sm text-slate-400">第71天生产评估平台关联工作流 · 版本、检查点、恢复、回放与事件溯源</p></div></div><Link href="/" className="rounded-xl border border-white/10 px-4 py-2 text-xs font-bold text-slate-300 transition hover:bg-white/5">返回 Day71 对话工作台</Link></div> {/* 第71天：展示第71天徽标、生产化升级第8版、继承工作流描述与返回入口。 */}
          <div className="mt-5 grid gap-2 sm:grid-cols-3 lg:grid-cols-5 xl:grid-cols-9">{metricCards.map((metric) => <article key={metric.label} className="rounded-2xl border border-white/10 bg-slate-950/55 p-3"><p className="text-[11px] text-slate-500">{metric.label}</p><p className="mt-2 font-mono text-xl font-black text-violet-200">{metric.value}</p></article>)}</div> {/* 第70天：展示 Workflow Metrics V2 九项核心指标。 */}
        </header> {/* 第70天：结束持久化工作流平台标题区。 */}
        <section className="mt-4 rounded-3xl border border-white/10 bg-slate-950/70 p-4"> {/* 第70天：定义创建冻结版本执行的控制区。 */}
          <div className="grid gap-3 lg:grid-cols-[1fr_160px_auto_auto]"><input value={query} onChange={(event) => setQuery(event.target.value)} className="rounded-xl border border-white/10 bg-[#07111f] px-4 py-2.5 text-sm outline-none focus:border-violet-300/50" aria-label="第71天评估关联工作流输入" /><select value={version} onChange={(event) => setVersion(Number(event.target.value))} className="rounded-xl border border-white/10 bg-[#07111f] px-4 py-2.5 text-sm"><option value={1}>research-flow V1</option><option value={2}>research-flow V2</option></select><button type="button" disabled={loading} onClick={() => void requestAction("POST", { action: "start_execution", workflowId: "research-flow", workflowVersion: version, query })} className="rounded-xl bg-violet-300 px-4 py-2.5 text-sm font-black text-slate-950 disabled:opacity-50">启动持久化执行</button><button type="button" disabled={loading || version !== 2} onClick={() => void requestAction("POST", { action: "start_execution", workflowId: "research-flow", workflowVersion: 2, query, simulateInterruptionAfterStepId: "critic" })} className="rounded-xl border border-cyan-300/30 px-4 py-2.5 text-sm font-bold text-cyan-200 disabled:opacity-40">模拟检查点后重启</button></div> {/* 第71天：提供评估关联的版本选择、查询输入、正常启动与可靠检查点后中断动作。 */}
          {error ? <p className="mt-3 rounded-xl border border-rose-300/20 bg-rose-300/10 p-3 text-sm text-rose-100">{error}</p> : null} {/* 第70天：按需展示平台请求错误。 */}
        </section> {/* 第70天：结束新执行控制区。 */}
        <nav className="mt-4 grid gap-2 rounded-3xl border border-white/10 bg-slate-950/70 p-2 md:grid-cols-3" role="tablist" aria-label="第71天生产评估平台关联持久化工作流标签页">{TABS.map((tab) => <button key={tab.id} type="button" role="tab" aria-selected={activeTab === tab.id} onClick={() => setActiveTab(tab.id)} className={`rounded-2xl px-4 py-3 text-left transition ${activeTab === tab.id ? "bg-violet-300 text-slate-950" : "text-slate-400 hover:bg-white/5 hover:text-white"}`}><span className="block text-sm font-black">{tab.label}</span><span className={`mt-1 block text-[11px] ${activeTab === tab.id ? "text-slate-700" : "text-slate-600"}`}>{tab.description}</span></button>)}</nav> {/* 第71天：渲染带 Day71 相关标题的 Catalog、Execution 与 Replay 三个标签页。 */}
        {!snapshot ? <div className="mt-4 rounded-3xl border border-dashed border-violet-300/25 py-24 text-center text-violet-200">正在初始化 Workflow Definition V2、State Store V2、Checkpoint、Event Sourcing 与 Replay Engine…</div> : null} {/* 第70天：快照未就绪时展示平台能力初始化占位。 */}
        {snapshot && activeTab === "catalog" ? <section className="mt-4 grid gap-4 xl:grid-cols-2"> {/* 第70天：按需渲染 Workflow Catalog 标签页。 */}
          {snapshot.definitions.map((definition) => <article key={`${definition.id}@${definition.version}`} className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wider text-violet-300">{definition.id} · Version {definition.version}</p><h2 className="mt-1 text-xl font-black">{definition.name}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{definition.description}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${statusClass(definition.status)}`}>{definition.status}</span></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs text-slate-500"><span>Owner：{definition.owner}</span><span>Updated：{formatTime(definition.updatedAt)}</span></div><ol className="mt-4 space-y-2">{definition.steps.map((step, index) => <li key={step.id} className="rounded-2xl border border-white/10 bg-white/[0.03] p-3"><div className="flex items-center justify-between gap-3"><p className="font-bold text-slate-200">{index + 1}. {step.name}</p><span className="font-mono text-[10px] text-violet-200">{step.handler}</span></div><p className="mt-1 text-[11px] text-slate-500">Depends：{step.dependsOn?.join("、") || "无"}{step.requiresConfirmation ? " · HITL 人工确认" : ""}</p></li>)}</ol></article>)} {/* 第70天：展示同一工作流 V1/V2 并存、负责人、状态、更新时间和冻结步骤。 */}
        </section> : null} {/* 第70天：结束 Workflow Catalog 标签页条件渲染。 */}
        {snapshot && activeTab === "executions" ? <section className="mt-4 space-y-3"> {/* 第70天：按需渲染 Execution Explorer 标签页。 */}
          {snapshot.executions.map((execution) => { const state = stateByExecution.get(execution.id); const definition = definitionByExecution.get(`${execution.workflowId}@${execution.workflowVersion}`); const duration = (execution.completedAt ?? execution.updatedAt) - execution.startedAt; return <article key={execution.id} className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-[11px] text-violet-300">{execution.id}</p><h2 className="mt-1 text-lg font-black">{definition?.name ?? execution.workflowId} V{execution.workflowVersion}</h2></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${statusClass(execution.status)}`}>{execution.status}</span></div><div className="mt-4 grid gap-2 text-xs text-slate-400 sm:grid-cols-2 lg:grid-cols-5"><span>Duration：{duration}ms</span><span>Current：{execution.currentStepId ?? "—"}</span><span>Completed：{state?.completedSteps.length ?? 0}/{definition?.steps.length ?? 0}</span><span>Checkpoint：{state?.checkpoints.length ?? 0}</span><span>Resume / Retry：{execution.resumeCount} / {execution.retryCount}</span></div><div className="mt-4 flex flex-wrap gap-2">{execution.status === "paused" || execution.status === "failed" ? <button type="button" disabled={loading} onClick={() => void requestAction("PATCH", { action: "resume_execution", executionId: execution.id })} className="rounded-xl bg-cyan-300 px-3 py-2 text-xs font-black text-slate-950">Resume（恢复）</button> : null}{execution.status === "waiting" ? <button type="button" disabled={loading} onClick={() => void requestAction("PATCH", { action: "approve_execution", executionId: execution.id })} className="rounded-xl bg-amber-300 px-3 py-2 text-xs font-black text-slate-950">Confirm &amp; Resume（确认并恢复）</button> : null}<button type="button" disabled={loading} onClick={() => { setActiveTab("replay"); void requestAction("PATCH", { action: "replay_execution", executionId: execution.id }); }} className="rounded-xl border border-violet-300/30 px-3 py-2 text-xs font-bold text-violet-200">Replay（回放）</button>{!["completed", "cancelled"].includes(execution.status) ? <button type="button" disabled={loading} onClick={() => void requestAction("PATCH", { action: "cancel_execution", executionId: execution.id })} className="rounded-xl border border-rose-300/30 px-3 py-2 text-xs font-bold text-rose-200">Cancel（取消）</button> : null}</div>{execution.error ? <p className="mt-3 rounded-xl bg-rose-300/10 p-3 text-xs text-rose-100">{execution.error}</p> : null}</article>; })} {/* 第70天：展示执行版本、状态、时长、当前步骤、检查点与恢复、回放、取消动作。 */}
        </section> : null} {/* 第70天：结束 Execution Explorer 标签页条件渲染。 */}
        {snapshot && activeTab === "replay" ? <section className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1.25fr)_minmax(360px,0.75fr)]"> {/* 第70天：按需渲染 Replay Debug 标签页。 */}
          <div className="space-y-4"><article className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wider text-violet-300">Event Timeline（事件时间线）</p><h2 className="mt-1 text-lg font-black">{snapshot.lastReplay ? `${snapshot.lastReplay.executionId} · V${snapshot.lastReplay.workflowVersion}` : "请选择一个执行实例回放"}</h2></div>{snapshot.lastReplay ? <span className={`rounded-full px-3 py-1 text-xs font-bold ${statusClass(snapshot.lastReplay.reconstructedStatus)}`}>{snapshot.lastReplay.reconstructedStatus}</span> : null}</div><div className="mt-4 space-y-2">{snapshot.lastReplay?.timeline.map((event) => <div key={event.id} className="grid gap-2 rounded-2xl border border-white/10 bg-white/[0.03] p-3 sm:grid-cols-[52px_1fr_auto]"><span className="font-mono text-xs font-black text-violet-200">#{event.sequence}</span><div><p className="text-sm font-bold">{event.type}</p><p className="mt-1 text-[11px] text-slate-500">Step：{event.stepId ?? "—"} · {JSON.stringify(event.payload)}</p></div><span className="text-[10px] text-slate-600">{formatTime(event.timestamp)}</span></div>) ?? <p className="text-sm text-slate-500">暂无回放时间线。</p>}</div></article><article className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><h2 className="font-black">Checkpoint &amp; Step Output（检查点与步骤输出）</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{snapshot.lastReplay?.checkpoints.map((checkpoint) => <div key={checkpoint.id} className="rounded-2xl bg-white/[0.03] p-3"><div className="flex items-center justify-between gap-2"><p className="font-bold text-slate-200">{checkpoint.stepId}</p><span className={`rounded-full px-2 py-1 text-[10px] ${statusClass(checkpoint.status)}`}>{checkpoint.status}</span></div><p className="mt-2 break-all font-mono text-[10px] text-slate-600">{checkpoint.id}</p></div>)}</div><pre className="mt-4 max-h-80 overflow-auto whitespace-pre-wrap rounded-2xl bg-black/30 p-4 text-xs leading-6 text-cyan-100">{JSON.stringify(snapshot.lastReplay?.outputs ?? {}, null, 2)}</pre></article></div> {/* 第70天：展示完整事件时间线、检查点与直接复用的历史步骤输出。 */}
          <aside className="space-y-4"><article className="rounded-3xl border border-violet-300/15 bg-violet-300/5 p-5"><p className="text-xs font-black uppercase tracking-wider text-violet-300">Recovery Point（恢复点）</p><p className="mt-3 break-all font-mono text-sm text-violet-100">{snapshot.lastReplay?.recoveryCheckpointId ?? "暂无成功检查点"}</p><p className="mt-3 text-xs leading-5 text-slate-500">Replay 只读取 Event Log、Checkpoint 与 Step Output，不会重新调用模型或步骤处理器。</p></article><article className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><h2 className="font-black">RuntimeContext.workflowContext</h2><div className="mt-3 space-y-2">{snapshot.runtimeContexts.slice().reverse().slice(0, 5).map((context) => <pre key={context.requestId} className="overflow-auto rounded-xl bg-black/30 p-3 text-[10px] leading-5 text-cyan-100">{JSON.stringify(context.workflowContext, null, 2)}</pre>)}</div></article><article className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><h2 className="font-black">UnifiedRegistry（统一注册中心）</h2><ul className="mt-3 space-y-2">{snapshot.registryItems.map((item) => <li key={item.id} className="rounded-xl bg-white/[0.03] p-3"><div className="flex items-center justify-between gap-2"><p className="text-sm font-bold">{item.name}</p><span className="font-mono text-[10px] text-violet-200">{item.version}</span></div><p className="mt-1 text-[11px] text-slate-500">{String(item.metadata.description ?? "")}</p></li>)}</ul></article></aside> {/* 第70天：展示恢复点、workflowContext 与四类核心注册能力。 */}
        </section> : null} {/* 第70天：结束 Replay Debug 标签页条件渲染。 */}
      </div> {/* 第70天：结束响应式治理页面内容容器。 */}
    </main> // 第70天：结束深色 Workflow Explorer V2 页面。
  ); // 第70天：结束持久化工作流浏览器视图返回。
} // 第70天：结束 WorkflowExplorerV2 组件。
