"use client"; // 第71天：声明 Evaluation Explorer V2 需要标签页、请求和反馈表单交互能力。
import Link from "next/link"; // 第71天：引入 Next.js Link 实现返回主工作台的客户端导航。
import { useCallback, useEffect, useMemo, useState } from "react"; // 第71天：引入快照加载、派生数据、标签页和反馈表单所需 Hooks。
import { readApiData } from "@/lib/api/api-client"; // 第71天：引入统一 API 响应解析函数。
import type { EvaluationPlatformSnapshot, EvaluationRun, EvaluationScore } from "@/lib/evaluation/evaluation-platform-types"; // 第71天：引入评估平台快照、运行和多维评分类型。

type ExplorerTab = "runs" | "cases" | "regression" | "gate" | "loop"; // 第71天：定义任务要求的五个 Evaluation Explorer V2 标签页。
const TABS: { id: ExplorerTab; label: string; description: string }[] = [{ id: "runs", label: "Day71 Evaluation Runs（评估运行）", description: "Run ID、类型、数据集、评分与持续时间" }, { id: "cases", label: "Day71 Case Analysis（案例分析）", description: "输入、输出、期望、评分、引用与 Trace" }, { id: "regression", label: "Day71 Regression（回归比较）", description: "Baseline、Candidate、改进、退化与失败案例" }, { id: "gate", label: "Day71 Quality Gate（质量门禁）", description: "PASS / FAIL 与多维条件原因" }, { id: "loop", label: "Day71 Feedback Loop（反馈闭环）", description: "点踩、低分、Bad Case 与 Dataset 回归案例" }]; // 第71天：声明五个带 Day71 主题和中英文说明的标签页。
const SCORE_DIMENSIONS: { key: keyof EvaluationScore; label: string }[] = [{ key: "correctness", label: "正确性" }, { key: "relevance", label: "相关性" }, { key: "completeness", label: "完整性" }, { key: "safety", label: "安全性" }, { key: "latency", label: "延迟" }, { key: "cost", label: "成本" }, { key: "overall", label: "综合" }]; // 第71天：声明案例分析和回归比较展示的七个评分维度。
function formatTime(value?: number): string { return value ? new Date(value).toLocaleString("zh-CN", { hour12: false }) : "—"; } // 第71天：把毫秒时间戳格式化为中文本地时间。
function formatDuration(run: EvaluationRun): string { return `${Math.max(0, (run.completedAt ?? Date.now()) - run.startedAt)}ms`; } // 第71天：计算 EvaluationRun 开始到完成的持续时间。
function scoreClass(score: number): string { return score >= 8.5 ? "text-emerald-300" : score >= 7 ? "text-amber-300" : "text-rose-300"; } // 第71天：按高分、及格和低分选择评分展示颜色。
function statusClass(status: string): string { return status === "completed" || status === "passed" ? "bg-emerald-300/15 text-emerald-200" : status === "failed" ? "bg-rose-300/15 text-rose-200" : "bg-sky-300/15 text-sky-200"; } // 第71天：按完成、通过、失败和运行中状态选择徽标颜色。

export function EvaluationExplorerV2() { // 第71天：定义生产评估运行、案例、回归、门禁和反馈闭环浏览器。
  const [snapshot, setSnapshot] = useState<EvaluationPlatformSnapshot | null>(null); // 第71天：保存最近一次生产评估平台完整快照。
  const [activeTab, setActiveTab] = useState<ExplorerTab>("runs"); // 第71天：保存当前选中的 Day71 评估治理标签页。
  const [loading, setLoading] = useState(true); // 第71天：保存快照请求和反馈动作加载状态。
  const [error, setError] = useState(""); // 第71天：保存用户可读的平台请求错误。
  const [feedbackComment, setFeedbackComment] = useState("线上输出遗漏关键质量闭环，请沉淀为回归案例。"); // 第71天：保存负向反馈文字评论输入。
  const refresh = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/evaluations", { cache: "no-store" }); setSnapshot(await readApiData<EvaluationPlatformSnapshot>(response)); } catch (caught) { setError(caught instanceof Error ? caught.message : "加载生产评估平台失败"); } finally { setLoading(false); } }, []); // 第71天：定义读取数据集、运行、结果、回归、门禁、反馈、链路和指标快照的稳定动作。
  useEffect(() => { const timer = window.setTimeout(() => void refresh(), 0); return () => window.clearTimeout(timer); }, [refresh]); // 第71天：组件挂载后异步初始化示例平台并在卸载时清理定时器。
  const submitNegativeFeedback = useCallback(async (resultId: string) => { setLoading(true); setError(""); try { const response = await fetch("/api/evaluations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "submit_feedback", resultId, sentiment: "negative", rating: 2, comment: feedbackComment }) }); const data = await readApiData<{ snapshot: EvaluationPlatformSnapshot }>(response); setSnapshot(data.snapshot); setActiveTab("loop"); } catch (caught) { setError(caught instanceof Error ? caught.message : "提交第71天反馈闭环失败"); } finally { setLoading(false); } }, [feedbackComment]); // 第71天：定义点踩、两分和评论自动形成 Bad Case 的反馈动作。
  const datasetById = useMemo(() => new Map((snapshot?.datasets ?? []).map((dataset) => [dataset.id, dataset])), [snapshot]); // 第71天：建立数据集标识到 Evaluation Dataset V2 的快速查找表。
  const runById = useMemo(() => new Map((snapshot?.runs ?? []).map((run) => [run.id, run])), [snapshot]); // 第71天：建立 EvaluationRun 标识到运行对象的快速查找表。
  const resultById = useMemo(() => new Map((snapshot?.results ?? []).map((result) => [result.id, result])), [snapshot]); // 第71天：建立单案例结果标识到案例分析对象的快速查找表。
  const metrics = snapshot?.metrics; // 第71天：读取 Evaluation Metrics V2 供顶部指标卡片展示。
  const metricCards = [{ label: "运行总数", value: metrics?.totalRuns ?? 0 }, { label: "成功率", value: `${((metrics?.successRate ?? 0) * 100).toFixed(0)}%` }, { label: "平均评分", value: (metrics?.avgScore ?? 0).toFixed(2) }, { label: "平均延迟", value: `${metrics?.avgLatency ?? 0}ms` }, { label: "平均成本", value: `$${(metrics?.avgCost ?? 0).toFixed(4)}` }, { label: "回归次数", value: metrics?.regressionCount ?? 0 }, { label: "Bad Case", value: metrics?.badCaseCount ?? 0 }, { label: "门禁失败", value: metrics?.qualityGateFailCount ?? 0 }, { label: "评估器调用", value: metrics?.evaluatorUsage ?? 0 }]; // 第71天：整理任务清单要求的九项生产评估指标卡片。
  return ( // 第71天：返回深色生产评估治理台完整视图。
    <main className="h-full min-h-screen overflow-y-auto bg-[#071019] text-slate-100"> {/* 第71天：定义可独立滚动的深色 Evaluation Explorer V2 页面。 */}
      <div className="mx-auto w-full max-w-[1680px] p-4 sm:p-6"> {/* 第71天：定义响应式评估治理页面内容容器。 */}
        <header className="rounded-3xl border border-fuchsia-300/15 bg-[radial-gradient(circle_at_top_left,rgba(232,121,249,0.16),transparent_34%),linear-gradient(135deg,#111827,#071019_55%,#082f49)] p-5 shadow-2xl shadow-black/30"> {/* 第71天：定义生产评估平台渐变标题区。 */}
          <div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-center gap-4"><div className="flex size-14 flex-col items-center justify-center rounded-2xl bg-fuchsia-300 text-slate-950"><span className="text-[9px] font-black uppercase">Day</span><span className="font-mono text-2xl font-black">71</span></div><div><p className="text-xs font-black uppercase tracking-[0.22em] text-fuchsia-200">Production Upgrade V8</p><h1 className="mt-1 text-2xl font-black sm:text-3xl">Production Evaluation Platform V2</h1><p className="mt-2 text-sm text-slate-400">生产评估平台第2版 · Observe → Evaluate → Diagnose → Improve → Validate</p></div></div><div className="flex flex-wrap gap-2"><button type="button" disabled={loading} onClick={() => void refresh()} className="rounded-xl border border-fuchsia-300/30 px-4 py-2 text-xs font-bold text-fuchsia-100 transition hover:bg-fuchsia-300/10 disabled:opacity-50">刷新评估快照</button><Link href="/" className="rounded-xl border border-white/10 px-4 py-2 text-xs font-bold text-slate-300 transition hover:bg-white/5">返回 Day71 对话工作台</Link></div></div> {/* 第71天：展示 Day71 徽标、生产化升级标题、持续改进闭环和导航动作。 */}
          <div className="mt-5 grid gap-2 sm:grid-cols-3 lg:grid-cols-5 xl:grid-cols-9">{metricCards.map((metric) => <article key={metric.label} className="rounded-2xl border border-white/10 bg-slate-950/55 p-3"><p className="text-[11px] text-slate-500">{metric.label}</p><p className="mt-2 font-mono text-xl font-black text-fuchsia-200">{metric.value}</p></article>)}</div> {/* 第71天：展示 Evaluation Metrics V2 九项核心指标。 */}
        </header> {/* 第71天：结束生产评估平台标题区。 */}
        {error ? <p className="mt-4 rounded-2xl border border-rose-300/20 bg-rose-300/10 p-4 text-sm text-rose-100">{error}</p> : null} {/* 第71天：按需展示生产评估平台请求错误。 */}
        <nav className="mt-4 grid gap-2 rounded-3xl border border-white/10 bg-slate-950/70 p-2 md:grid-cols-5" role="tablist" aria-label="Day 71 Production Evaluation Platform V2 标签页">{TABS.map((tab) => <button key={tab.id} type="button" role="tab" aria-selected={activeTab === tab.id} onClick={() => setActiveTab(tab.id)} className={`rounded-2xl px-4 py-3 text-left transition ${activeTab === tab.id ? "bg-fuchsia-300 text-slate-950" : "text-slate-400 hover:bg-white/5 hover:text-white"}`}><span className="block text-sm font-black">{tab.label}</span><span className={`mt-1 block text-[11px] ${activeTab === tab.id ? "text-slate-700" : "text-slate-600"}`}>{tab.description}</span></button>)}</nav> {/* 第71天：渲染带 Day71 相关标题的五个生产评估标签页。 */}
        {!snapshot ? <div className="mt-4 rounded-3xl border border-dashed border-fuchsia-300/25 py-24 text-center text-fuchsia-200">正在初始化 EvaluationRun、Dataset V2、多维评估、Quality Gate 和 Feedback Loop…</div> : null} {/* 第71天：快照未就绪时展示生产评估能力初始化占位。 */}
        {snapshot && activeTab === "runs" ? <section className="mt-4 space-y-3"> {/* 第71天：按需渲染 Evaluation Runs 评估运行列表标签页。 */}
          {snapshot.runs.map((run) => <article key={run.id} className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-[11px] text-fuchsia-300">{run.id}</p><h2 className="mt-1 text-lg font-black">{run.label}</h2><p className="mt-1 text-xs text-slate-500">{datasetById.get(run.datasetId ?? "")?.name ?? run.datasetId ?? "无数据集"}</p></div><div className="flex gap-2"><span className="rounded-full bg-sky-300/15 px-3 py-1 text-xs font-bold text-sky-200">{run.type}</span><span className={`rounded-full px-3 py-1 text-xs font-bold ${statusClass(run.status)}`}>{run.status}</span></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-5"><div><p className="text-[11px] text-slate-600">Score</p><p className={`mt-1 font-mono text-2xl font-black ${scoreClass(run.score)}`}>{run.score.toFixed(2)}</p></div><div><p className="text-[11px] text-slate-600">Duration</p><p className="mt-1 font-mono text-sm text-slate-300">{formatDuration(run)}</p></div><div><p className="text-[11px] text-slate-600">Average Latency</p><p className="mt-1 font-mono text-sm text-slate-300">{run.usage.latencyMs}ms</p></div><div><p className="text-[11px] text-slate-600">Average Cost</p><p className="mt-1 font-mono text-sm text-slate-300">${run.usage.cost.toFixed(4)}</p></div><div><p className="text-[11px] text-slate-600">Runtime / Trace</p><p className="mt-1 break-all font-mono text-[10px] text-cyan-200">{run.runtimeContextId}<br />{run.traceIds.join("、")}</p></div></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4 xl:grid-cols-7">{SCORE_DIMENSIONS.map((dimension) => <div key={dimension.key} className="rounded-xl bg-white/[0.03] p-3"><p className="text-[10px] text-slate-600">{dimension.label}</p><p className={`mt-1 font-mono text-lg font-black ${scoreClass(run.scores[dimension.key])}`}>{run.scores[dimension.key].toFixed(2)}</p></div>)}</div></article>)} {/* 第71天：展示 Run ID、类型、数据集、评分、时长、用量、Context、Trace 和七维评分。 */}
        </section> : null} {/* 第71天：结束 Evaluation Runs 标签页条件渲染。 */}
        {snapshot && activeTab === "cases" ? <section className="mt-4 grid gap-4 xl:grid-cols-2"> {/* 第71天：按需渲染 Case Analysis 案例分析标签页。 */}
          {snapshot.results.map((result) => <article key={result.id} className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-[10px] text-fuchsia-300">{result.caseId}</p><h2 className="mt-1 font-black">{runById.get(result.runId)?.label ?? result.runId}</h2></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${result.passed ? statusClass("passed") : statusClass("failed")}`}>{result.passed ? "PASS" : "FAIL"}</span></div><div className="mt-4 grid gap-3 lg:grid-cols-3"><div className="rounded-2xl bg-white/[0.03] p-3"><p className="text-[10px] font-black uppercase tracking-wider text-sky-300">Input</p><p className="mt-2 text-xs leading-5 text-slate-300">{result.input}</p></div><div className="rounded-2xl bg-white/[0.03] p-3"><p className="text-[10px] font-black uppercase tracking-wider text-emerald-300">Output</p><p className="mt-2 text-xs leading-5 text-slate-300">{result.output}</p></div><div className="rounded-2xl bg-white/[0.03] p-3"><p className="text-[10px] font-black uppercase tracking-wider text-amber-300">Expected</p><p className="mt-2 text-xs leading-5 text-slate-300">{result.expected}</p></div></div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4 xl:grid-cols-7">{SCORE_DIMENSIONS.map((dimension) => <div key={dimension.key} className="rounded-xl border border-white/5 p-2"><p className="text-[9px] text-slate-600">{dimension.label}</p><p className={`mt-1 font-mono font-black ${scoreClass(result.scores[dimension.key])}`}>{result.scores[dimension.key].toFixed(2)}</p></div>)}</div><div className="mt-4 flex flex-wrap items-center gap-2 text-[10px] text-slate-500"><span className="break-all text-cyan-200">Trace：{result.traceId}</span><span>引用：{result.citations.join("、") || "无"}</span><span>{formatTime(result.completedAt)}</span></div><details className="mt-3 rounded-2xl border border-white/10 p-3"><summary className="cursor-pointer text-xs font-bold text-fuchsia-200">Evaluator Versions &amp; Reasons（评估器版本与原因）</summary><div className="mt-3 space-y-2">{result.evaluatorOutputs.map((output) => <div key={output.evaluatorId} className="rounded-xl bg-black/20 p-3"><p className="font-mono text-[10px] text-fuchsia-300">{output.evaluatorId}@{output.evaluatorVersion}</p><p className="mt-1 text-[11px] text-slate-400">{output.reasons.join("；")}</p></div>)}</div></details>{!result.passed ? <button type="button" disabled={loading} onClick={() => void submitNegativeFeedback(result.id)} className="mt-3 rounded-xl bg-rose-300 px-3 py-2 text-xs font-black text-slate-950 disabled:opacity-50">👎 2分并沉淀 Bad Case</button> : null}</article>)} {/* 第71天：展示输入、输出、期望、七维评分、Trace、引用、评估器版本和低分反馈动作。 */}
        </section> : null} {/* 第71天：结束 Case Analysis 标签页条件渲染。 */}
        {snapshot && activeTab === "regression" ? <section className="mt-4 space-y-4"> {/* 第71天：按需渲染 Regression 回归比较标签页。 */}
          {snapshot.regressions.map((comparison) => { const baseline = runById.get(comparison.baselineRunId); const candidate = runById.get(comparison.candidateRunId); return <article key={comparison.id} className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><div className="grid gap-3 lg:grid-cols-[1fr_auto_1fr]"><div className="rounded-2xl bg-sky-300/5 p-4"><p className="text-xs font-black uppercase tracking-wider text-sky-300">Baseline</p><h2 className="mt-2 font-black">{baseline?.label}</h2><p className="mt-1 font-mono text-2xl text-sky-200">{baseline?.score.toFixed(2)}</p></div><div className="flex items-center justify-center text-2xl text-slate-600">→</div><div className="rounded-2xl bg-fuchsia-300/5 p-4"><p className="text-xs font-black uppercase tracking-wider text-fuchsia-300">Candidate</p><h2 className="mt-2 font-black">{candidate?.label}</h2><p className="mt-1 font-mono text-2xl text-fuchsia-200">{candidate?.score.toFixed(2)}</p></div></div><div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-2xl bg-emerald-300/5 p-4"><p className="text-xs font-black text-emerald-300">Improved Cases（改进）</p><p className="mt-2 text-sm text-slate-300">{comparison.improvedCases.join("、") || "无"}</p></div><div className="rounded-2xl bg-amber-300/5 p-4"><p className="text-xs font-black text-amber-300">Regressed Cases（退化）</p><p className="mt-2 text-sm text-slate-300">{comparison.regressedCases.join("、") || "无"}</p></div><div className="rounded-2xl bg-rose-300/5 p-4"><p className="text-xs font-black text-rose-300">Failed Cases（失败）</p><p className="mt-2 text-sm text-slate-300">{comparison.failedCases.join("、") || "无"}</p></div></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4 xl:grid-cols-7">{SCORE_DIMENSIONS.map((dimension) => <div key={dimension.key} className="rounded-xl border border-white/5 p-3"><p className="text-[10px] text-slate-600">Δ {dimension.label}</p><p className={`mt-1 font-mono text-lg font-black ${comparison.scoreDeltas[dimension.key] >= 0 ? "text-emerald-300" : "text-rose-300"}`}>{comparison.scoreDeltas[dimension.key] >= 0 ? "+" : ""}{comparison.scoreDeltas[dimension.key].toFixed(2)}</p></div>)}</div></article>; })} {/* 第71天：展示 Baseline、Candidate、改进、退化、失败案例和七维变化。 */}
        </section> : null} {/* 第71天：结束 Regression 标签页条件渲染。 */}
        {snapshot && activeTab === "gate" ? <section className="mt-4 grid gap-4 xl:grid-cols-2"> {/* 第71天：按需渲染 Quality Gate 质量门禁标签页。 */}
          {snapshot.qualityGates.map((gate) => <article key={gate.id} className={`rounded-3xl border p-5 ${gate.status === "passed" ? "border-emerald-300/20 bg-emerald-300/5" : "border-rose-300/20 bg-rose-300/5"}`}><div className="flex items-center justify-between gap-3"><div><p className="font-mono text-[10px] text-slate-500">{gate.id}</p><h2 className="mt-1 text-xl font-black">Quality Gate V2</h2></div><span className={`rounded-full px-4 py-2 text-sm font-black ${statusClass(gate.status)}`}>{gate.status.toUpperCase()}</span></div><div className="mt-4 space-y-2">{gate.checks.map((check) => <div key={check.id} className="rounded-2xl border border-white/10 bg-slate-950/60 p-4"><div className="flex items-start justify-between gap-3"><p className="text-sm font-bold text-slate-200">{check.label}</p><span className={check.passed ? "text-emerald-300" : "text-rose-300"}>{check.passed ? "PASS" : "FAIL"}</span></div><p className="mt-2 font-mono text-xs text-slate-500">{check.detail}</p></div>)}</div><p className="mt-4 rounded-2xl bg-black/20 p-4 text-sm text-slate-300">Reasons：{gate.reasons.join("；") || "全部多维质量门禁条件通过，候选版本允许晋级。"}</p></article>)} {/* 第71天：展示 PASS、FAIL、综合分、正确性、高优先级通过率、成本和判断原因。 */}
        </section> : null} {/* 第71天：结束 Quality Gate 标签页条件渲染。 */}
        {snapshot && activeTab === "loop" ? <section className="mt-4 grid gap-4 xl:grid-cols-[0.9fr_1.1fr]"> {/* 第71天：按需渲染 Feedback Loop 反馈闭环标签页。 */}
          <div className="space-y-4"><article className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><h2 className="text-lg font-black">用户反馈输入（👍 / 👎 / rating / comment）</h2><textarea value={feedbackComment} onChange={(event) => setFeedbackComment(event.target.value)} className="mt-4 min-h-28 w-full rounded-2xl border border-white/10 bg-[#071019] p-4 text-sm outline-none focus:border-fuchsia-300/40" aria-label="第71天用户反馈评论" /><p className="mt-3 text-xs leading-5 text-slate-500">可在 Case Analysis 中对低分案例提交 👎 与 2 分；平台会自动创建 Bad Case、追加 Dataset 案例并发布 bad_case.created 事件。</p></article><article className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><h2 className="font-black">Feedback Records（反馈记录）</h2><div className="mt-3 space-y-2">{snapshot.feedback.map((item) => <div key={item.id} className="rounded-2xl bg-white/[0.03] p-3"><div className="flex items-center justify-between gap-2"><span className={item.sentiment === "negative" ? "text-rose-300" : "text-emerald-300"}>{item.sentiment === "negative" ? "👎" : "👍"} {item.rating}/5</span><span className="text-[10px] text-slate-600">{formatTime(item.createdAt)}</span></div><p className="mt-2 text-xs text-slate-400">{item.comment || "无文字评论"}</p></div>)}</div></article></div> {/* 第71天：展示用户反馈输入说明和历史点赞、点踩、评分与评论。 */}
          <div className="space-y-4"><article className="rounded-3xl border border-rose-300/15 bg-rose-300/5 p-5"><h2 className="text-lg font-black text-rose-200">Bad Case Loop（坏案例闭环）</h2><div className="mt-4 flex flex-wrap items-center gap-2 text-xs font-bold"><span className="rounded-full bg-rose-300/15 px-3 py-2 text-rose-200">线上失败</span><span>→</span><span className="rounded-full bg-amber-300/15 px-3 py-2 text-amber-200">Bad Case</span><span>→</span><span className="rounded-full bg-sky-300/15 px-3 py-2 text-sky-200">Evaluation Dataset</span><span>→</span><span className="rounded-full bg-emerald-300/15 px-3 py-2 text-emerald-200">Regression Test</span></div><div className="mt-4 space-y-3">{snapshot.badCases.map((item) => <div key={item.id} className="rounded-2xl border border-white/10 bg-slate-950/60 p-4"><p className="font-mono text-[10px] text-rose-300">{item.id}</p><p className="mt-2 text-sm font-bold">{item.reason}</p><p className="mt-2 break-all text-[11px] text-slate-500">Dataset：{item.datasetId}<br />Regression Case：{item.evaluationCaseId}<br />Source Result：{resultById.get(item.sourceResultId)?.caseId ?? item.sourceResultId}</p></div>)}</div></article><article className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><h2 className="font-black">RuntimeContext / EventBus / UnifiedRegistry</h2><div className="mt-3 grid gap-3 md:grid-cols-3"><div className="rounded-2xl bg-white/[0.03] p-3"><p className="text-xs font-black text-cyan-300">evaluationContext</p><pre className="mt-2 max-h-48 overflow-auto whitespace-pre-wrap text-[9px] leading-4 text-slate-500">{JSON.stringify(snapshot.runtimeContexts[0]?.evaluationContext ?? {}, null, 2)}</pre></div><div className="rounded-2xl bg-white/[0.03] p-3"><p className="text-xs font-black text-amber-300">EventBus</p><ul className="mt-2 space-y-1 text-[10px] text-slate-500">{snapshot.events.slice(0, 12).map((event) => <li key={event.id}>{event.type}</li>)}</ul></div><div className="rounded-2xl bg-white/[0.03] p-3"><p className="text-xs font-black text-fuchsia-300">UnifiedRegistry</p><ul className="mt-2 space-y-1 text-[10px] text-slate-500">{snapshot.registryItems.map((item) => <li key={item.id}>{item.name}</li>)}</ul></div></div></article></div> {/* 第71天：展示线上失败到回归测试闭环以及 RuntimeContext、EventBus 和 UnifiedRegistry 接入证据。 */}
        </section> : null} {/* 第71天：结束 Feedback Loop 标签页条件渲染。 */}
      </div> {/* 第71天：结束响应式评估治理页面内容容器。 */}
    </main> // 第71天：结束深色生产评估浏览器页面。
  ); // 第71天：结束 Evaluation Explorer V2 视图返回。
} // 第71天：结束 EvaluationExplorerV2 组件。
