import { MemoryEventBus } from "@/lib/events/memory-event-bus"; // 第69天：引入统一事件总线记录知识与检索生命周期事件。
import { ObjectStorageKnowledgeAdapter, ProductionKnowledgeRepository, RedisKnowledgeJobQueue, ResilientKnowledgeLockProvider } from "@/lib/knowledge/production-knowledge-infrastructure"; // 第69天：引入对象存储、元数据仓储、Redis Queue 与弹性分布式锁实现。
import { ProductionKnowledgeService } from "@/lib/knowledge/production-knowledge-service"; // 第69天：引入生产知识统一外观服务。
import type { KnowledgeAccessContext, KnowledgeBaseStatus, KnowledgeScope, ProductionKnowledgePlatformSnapshot, ProductionRetrievalInput } from "@/lib/knowledge/production-knowledge-types"; // 第69天：引入平台动作、权限上下文、检索输入和治理快照类型。
import { createDay66UnifiedRegistry } from "@/lib/registry/registry-runtime"; // 第69天：复用包含历史能力的统一注册中心作为生产知识平台基础。
import type { UnifiedRegistry } from "@/lib/registry/unified-registry"; // 第69天：引入统一注册中心类型注册可替换知识能力。
import { runtimeContextBuilder } from "@/lib/runtime/unified-runtime-context"; // 第69天：引入统一运行时上下文构建器演示检索上下文注入。
import { objectStorageClient } from "@/lib/storage/object-storage-client"; // 第69天：引入真实对象存储客户端并由配置中心决定本地或 MinIO 后端。
const DAY69_CREATED_AT = Date.UTC(2026, 6, 17, 0, 0, 0); // 第69天：定义生产知识能力使用的稳定教学创建时间戳。
export function registerProductionKnowledgeCapabilities(registry: UnifiedRegistry): void { // 第69天：向统一注册中心登记服务、策略、Provider、解析器和引用格式化器。
  registry.upsert({ id: "knowledge:service:production", name: "ProductionKnowledgeService（生产知识服务）", type: "knowledge", version: "day69.v1", metadata: { description: "统一协调对象存储、元数据、Redis Queue、分布式锁、VectorStore、事件和 RuntimeContext", capabilities: ["knowledge-lifecycle", "asynchronous-indexing", "retrieval-v2", "governance"], tags: ["knowledge", "rag", "service", "facade"] }, enabled: true, createdAt: DAY69_CREATED_AT }); // 第69天：注册生产知识统一外观服务。
  registry.upsert({ id: "knowledge:strategy:chunk:sliding-window", name: "SlidingWindowChunkStrategy（滑动窗口切块策略）", type: "knowledge", version: "day69.v1", metadata: { description: "使用 320 字符窗口和 64 字符重叠生成可定位片段", capabilities: ["chunking", "overlap", "incremental-index"], tags: ["knowledge", "chunk", "strategy"] }, enabled: true, createdAt: DAY69_CREATED_AT }); // 第69天：注册可替换切块策略。
  registry.upsert({ id: "knowledge:strategy:retrieval:production-v2", name: "ProductionRetrievalPipelineV2（生产检索管线第2版）", type: "knowledge", version: "day69.v1", metadata: { description: "支持权限过滤、记忆感知改写、多查询、混合召回、活动版本过滤、重排与引用", capabilities: ["permission-filter", "multi-query", "hybrid-search", "rerank", "citation"], tags: ["knowledge", "retrieval", "rag"] }, enabled: true, createdAt: DAY69_CREATED_AT }); // 第69天：注册生产检索策略第二版。
  registry.upsert({ id: "knowledge:provider:embedding:deterministic", name: "DeterministicEmbeddingProvider（确定性向量提供者）", type: "knowledge", version: "day69.v1", metadata: { description: "提供可离线测试的稳定向量并保留替换真实 Embedding Provider 的接口边界", capabilities: ["embedding", "cache", "offline-test"], tags: ["knowledge", "embedding", "provider"] }, enabled: true, createdAt: DAY69_CREATED_AT }); // 第69天：注册教学环境确定性向量 Provider。
  registry.upsert({ id: "knowledge:parser:text", name: "TextDocumentParser（文本文档解析器）", type: "knowledge", version: "day69.v1", metadata: { description: "解析 UTF-8 文本文档并为后续 PDF Parser 保留注册扩展点", capabilities: ["document-parser", "text"], tags: ["knowledge", "parser", "text"] }, enabled: true, createdAt: DAY69_CREATED_AT }); // 第69天：注册文本文档解析器。
  registry.upsert({ id: "knowledge:formatter:citation", name: "KnowledgeCitationFormatter（知识引用格式化器）", type: "knowledge", version: "day69.v1", metadata: { description: "生成可追溯到知识库、文档、片段、活动索引版本和对象键的标准引用", capabilities: ["citation", "traceability", "source-location"], tags: ["knowledge", "citation", "formatter"] }, enabled: true, createdAt: DAY69_CREATED_AT }); // 第69天：注册标准知识引用格式化器。
} // 第69天：结束生产知识能力注册函数。
export class ProductionKnowledgePlatform { // 第69天：组合生产知识服务、治理快照、示例数据和 API 动作的完整平台。
  readonly eventBus = new MemoryEventBus(320); // 第69天：创建容量受限的知识与检索事件总线。
  readonly repository = new ProductionKnowledgeRepository(); // 第69天：创建生产知识元数据、片段、向量与清单仓储。
  readonly storage = new ObjectStorageKnowledgeAdapter(objectStorageClient); // 第69天：创建对象存储适配器保存原始知识文档。
  readonly queue = new RedisKnowledgeJobQueue(); // 第69天：创建 Redis List 优先且故障自动降级的知识异步队列。
  readonly lockProvider = new ResilientKnowledgeLockProvider(); // 第69天：创建 Redis 分布式锁优先且故障自动降级的锁提供者。
  readonly registry = createDay66UnifiedRegistry(); // 第69天：创建继承历史能力的统一注册中心。
  readonly service = new ProductionKnowledgeService(this.repository, this.storage, this.queue, this.lockProvider, this.eventBus); // 第69天：注入全部基础设施创建生产知识统一服务。
  private seedPromise?: Promise<void>; // 第69天：保存示例数据初始化 Promise 避免并发请求重复播种。
  constructor() { registerProductionKnowledgeCapabilities(this.registry); } // 第69天：构造平台时立即注册六类可替换生产知识能力。
  async ensureDemoData(): Promise<void> { if (!this.seedPromise) this.seedPromise = this.seedDemoData(); return await this.seedPromise; } // 第69天：确保治理台教学数据只初始化一次且并发调用共享同一 Promise。
  private async seedDemoData(): Promise<void> { const workspaceBase = await this.service.createKnowledgeBase({ name: "Day69 生产 RAG 运行手册", description: "演示工作空间知识隔离、异步索引、活动版本和标准引用。", scope: "workspace", scopeId: "workspace-day69", createdBy: "day69-admin" }); const userBase = await this.service.createKnowledgeBase({ name: "用户 A 私有知识库", description: "验证用户 A 与用户 B 的私人知识权限隔离。", scope: "user", scopeId: "user-a", createdBy: "user-a" }); const globalBase = await this.service.createKnowledgeBase({ name: "全局公开工程规范", description: "演示 allowGlobalKnowledge 控制的公共知识。", scope: "global", scopeId: "global", createdBy: "day69-admin" }); await this.service.uploadDocument({ knowledgeBaseId: workspaceBase.id, title: "Production Knowledge Platform 操作手册", content: "生产知识平台上传文档后先进入 queued 状态，由 Redis Queue 中的 knowledge.index 任务异步处理。Indexer Worker 获取文档级分布式锁，完成切块、向量生成和 IndexManifest 保存后才发布活动索引版本。文档更新采用新版本后台构建，旧活动版本在切换前保持可检索。删除采用 deleting 到 deleted 的两阶段流程，并清理对象、片段、向量、索引清单和引用关系。", traceId: "trace-day69-seed-workspace", requestId: "request-day69-seed-workspace" }); await this.service.uploadDocument({ knowledgeBaseId: userBase.id, title: "用户 A 私有发布策略", content: "用户 A 的私人知识规定：索引发布前必须通过引用覆盖率和一致性检查，任何其他用户都不能检索本知识库内容。", traceId: "trace-day69-seed-private", requestId: "request-day69-seed-private" }); await this.service.uploadDocument({ knowledgeBaseId: globalBase.id, title: "知识引用规范", content: "标准 KnowledgeCitation 必须包含知识库、文档、片段、活动索引版本、引用摘录和对象存储键，Trace 中只保存 Citation ID 与必要定位信息。", traceId: "trace-day69-seed-global", requestId: "request-day69-seed-global" }); await this.service.drainJobs(); const runtimeContext = runtimeContextBuilder.build({ userId: "user-a", sessionId: "session-day69", taskId: "day69-demo-retrieval", traceId: "trace-day69-demo-retrieval", requestId: "request-day69-demo-retrieval", memoryContext: { preference: "用户关注索引版本、权限隔离和引用追溯" }, workspace: { workspaceId: "workspace-day69" } }); await this.service.retrieve({ query: "文档更新时怎样保证旧版本仍然可用？", runtimeContext, accessContext: { userId: "user-a", workspaceId: "workspace-day69" }, strategy: "quality", topK: 4, minScore: 0.08, requireCitations: true, allowGlobalKnowledge: true }); await this.service.scanKnowledgeConsistency(false); } // 第69天：生成覆盖工作空间、私人、全局、异步索引、引用和一致性扫描的治理台数据。
  private registryItems() { return this.registry.list("knowledge").filter((item) => item.version === "day69.v1"); } // 第69天：读取本平台新增的 Day69 生产知识注册项。
  async getSnapshot(seed = true): Promise<ProductionKnowledgePlatformSnapshot> { if (seed) await this.ensureDemoData(); return await this.service.getSnapshot(this.registryItems()); } // 第69天：生成治理浏览器和 API 共用的完整平台快照。
  async createKnowledgeBase(input: { name: string; description?: string; scope: KnowledgeScope; scopeId: string; createdBy?: string }): Promise<ProductionKnowledgePlatformSnapshot> { await this.service.createKnowledgeBase(input); return await this.getSnapshot(false); } // 第69天：创建生产知识库并返回最新治理快照。
  async uploadDocument(input: { knowledgeBaseId: string; title: string; content: string; mimeType?: string }): Promise<ProductionKnowledgePlatformSnapshot> { await this.service.uploadDocument(input); return await this.getSnapshot(false); } // 第69天：上传原始文档、排队索引并返回 queued 状态快照。
  async updateDocument(documentId: string, input: { title?: string; content: string; mimeType?: string }): Promise<ProductionKnowledgePlatformSnapshot> { await this.service.updateDocument(documentId, input); return await this.getSnapshot(false); } // 第69天：上传文档新版本并返回仍保留旧活动索引的快照。
  async rebuildDocument(documentId: string): Promise<ProductionKnowledgePlatformSnapshot> { await this.service.rebuildDocument(documentId); return await this.getSnapshot(false); } // 第69天：为文档创建新版本重建任务并返回最新快照。
  async retryFailedIndex(documentId: string): Promise<ProductionKnowledgePlatformSnapshot> { await this.service.retryFailedIndex(documentId); return await this.getSnapshot(false); } // 第69天：重新投递失败索引任务并返回最新快照。
  async processNextJob(): Promise<ProductionKnowledgePlatformSnapshot> { await this.service.processNextJob(); return await this.getSnapshot(false); } // 第69天：驱动一个 Indexer 或 Delete Worker 任务并返回最新快照。
  async drainJobs(): Promise<ProductionKnowledgePlatformSnapshot> { await this.service.drainJobs(); return await this.getSnapshot(false); } // 第69天：驱动 Worker 处理全部等待任务并返回最新快照。
  async retrieve(input: Omit<ProductionRetrievalInput, "runtimeContext"> & { runtimeContext?: ProductionRetrievalInput["runtimeContext"] }): Promise<ProductionKnowledgePlatformSnapshot> { const runtimeContext = input.runtimeContext ?? runtimeContextBuilder.build({ userId: input.accessContext.userId, sessionId: "session-day69-governance", traceId: `trace-day69-${Date.now()}`, workspace: { workspaceId: input.accessContext.workspaceId }, memoryContext: { focus: "索引版本、权限隔离、引用与一致性" } }); await this.service.retrieve({ ...input, runtimeContext }); return await this.getSnapshot(false); } // 第69天：执行生产检索第二版并把调试信息写入治理快照。
  async deleteDocument(documentId: string): Promise<ProductionKnowledgePlatformSnapshot> { await this.service.deleteDocument(documentId); return await this.getSnapshot(false); } // 第69天：把文档标记 deleting 并创建两阶段删除任务。
  async deleteKnowledgeBase(knowledgeBaseId: string): Promise<ProductionKnowledgePlatformSnapshot> { await this.service.deleteKnowledgeBase(knowledgeBaseId); return await this.getSnapshot(false); } // 第69天：把知识库及其文档全部进入两阶段删除流程。
  async setKnowledgeBaseStatus(knowledgeBaseId: string, status: KnowledgeBaseStatus): Promise<ProductionKnowledgePlatformSnapshot> { await this.service.setKnowledgeBaseStatus(knowledgeBaseId, status); return await this.getSnapshot(false); } // 第69天：启用、禁用、归档或标记删除知识库。
  async scanConsistency(autoRepairSafeItems = false): Promise<ProductionKnowledgePlatformSnapshot> { await this.service.scanKnowledgeConsistency(autoRepairSafeItems); return await this.getSnapshot(false); } // 第69天：执行一致性扫描并按需自动修复安全孤儿项。
  accessContext(input: KnowledgeAccessContext): KnowledgeAccessContext { return { userId: input.userId, workspaceId: input.workspaceId, teamIds: input.teamIds ?? [], isAdmin: input.isAdmin ?? false }; } // 第69天：标准化 API 或测试传入的知识访问上下文。
} // 第69天：结束生产知识平台组合实现。
const globalPlatform = globalThis as typeof globalThis & { day69ProductionKnowledgePlatform?: ProductionKnowledgePlatform }; // 第69天：扩展全局对象类型以在 Next.js 开发热更新期间复用平台状态。
export const productionKnowledgePlatform = globalPlatform.day69ProductionKnowledgePlatform ?? new ProductionKnowledgePlatform(); // 第69天：创建或复用进程级生产知识平台单例。
globalPlatform.day69ProductionKnowledgePlatform = productionKnowledgePlatform; // 第69天：保存平台单例以让 API 治理动作保持连续状态。
