"use client"; // 第73天：声明治理仪表盘需要标签页、刷新和筛选交互能力。
import Link from "next/link"; // 第73天：引入Next.js Link实现返回主工作台的客户端导航。
import { useCallback, useEffect, useMemo, useState } from "react"; // 第73天：引入快照加载、标签页和派生数据所需Hooks。
import { readApiData } from "@/lib/api/api-client"; // 第73天：引入统一API响应解析函数。
import type { AuditLog, GovernanceSnapshot } from "@/lib/governance/types"; // 第73天：引入治理平台快照和审计日志类型。
type DashboardTab = "overview" | "tenants" | "permissions" | "audit" | "quota" | "security"; // 第73天：定义治理总览、租户、权限、审计、配额和安全六个标签页。
const TABS: { id: DashboardTab; label: string; description: string }[] = [{ id: "overview", label: "Day73 Overview（总览）", description: "Production Ready治理闭环" }, { id: "tenants", label: "Tenant Explorer（租户）", description: "Users、Usage与Resources" }, { id: "permissions", label: "Permission Explorer（权限）", description: "Role、Permission与Mapping" }, { id: "audit", label: "Audit Explorer（审计）", description: "Who、When、What与Result" }, { id: "quota", label: "Quota Dashboard（配额）", description: "Token、Cost、Workflow与Storage" }, { id: "security", label: "Security Tests（安全）", description: "Gateway、EventBus与Registry" }]; // 第73天：声明六个带中英文说明的生产治理标签页。
function formatTime(value?: number): string { return value ? new Date(value).toLocaleString("zh-CN", { hour12: false }) : "—"; } // 第73天：把毫秒时间戳格式化为中文本地时间。
function resultClass(result: AuditLog["result"]): string { return result === "success" ? "bg-emerald-300/10 text-emerald-200" : result === "permission_denied" ? "bg-amber-300/10 text-amber-200" : "bg-rose-300/10 text-rose-200"; } // 第73天：按审计成功、权限拒绝和失败结果选择状态颜色。
function percent(current: number, limit: number): number { return limit <= 0 ? 0 : Math.min(100, Math.round((current / limit) * 100)); } // 第73天：把租户当前用量转换为不超过百分之一百的进度值。
export function GovernanceDashboard() { // 第73天：定义租户、权限、配额、审计、网关和安全测试一体化仪表盘。
  const [snapshot, setSnapshot] = useState<GovernanceSnapshot | null>(null); // 第73天：保存最近一次完整治理平台快照。
  const [activeTab, setActiveTab] = useState<DashboardTab>("overview"); // 第73天：保存当前选中的治理标签页。
  const [selectedTenantId, setSelectedTenantId] = useState("tenant-alpha"); // 第73天：保存Tenant Explorer当前查看的租户标识。
  const [loading, setLoading] = useState(true); // 第73天：保存治理快照加载状态。
  const [error, setError] = useState(""); // 第73天：保存用户可读的平台请求错误。
  const refresh = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/v1/governance", { cache: "no-store" }); setSnapshot(await readApiData<GovernanceSnapshot>(response)); } catch (caught) { setError(caught instanceof Error ? caught.message : "加载第73天智能体平台治理快照失败"); } finally { setLoading(false); } }, []); // 第73天：定义读取租户、权限、配额、审计和安全测试快照的稳定动作。
  useEffect(() => { const timer = window.setTimeout(() => void refresh(), 0); return () => window.clearTimeout(timer); }, [refresh]); // 第73天：组件挂载后异步初始化治理平台并在卸载时清理定时器。
  const selectedTenant = snapshot?.tenants.find((tenant) => tenant.id === selectedTenantId) ?? snapshot?.tenants[0]; // 第73天：读取当前选中租户或回退到第一个租户。
  const selectedMemberships = useMemo(() => (snapshot?.memberships ?? []).filter((item) => item.tenantId === selectedTenant?.id), [selectedTenant?.id, snapshot]); // 第73天：派生当前租户的用户角色映射。
  const selectedResources = useMemo(() => (snapshot?.resources ?? []).filter((item) => item.ownerContext.tenantId === selectedTenant?.id), [selectedTenant?.id, snapshot]); // 第73天：派生当前租户可见的全部归属资源。
  const selectedQuota = snapshot?.quotas.find((item) => item.tenant.id === selectedTenant?.id); // 第73天：读取当前租户的配额和用量。
  const cards = snapshot ? [{ label: "Tenants（租户）", value: snapshot.overview.tenants }, { label: "Active Users（启用用户）", value: snapshot.overview.activeUsers }, { label: "Owned Resources（归属资源）", value: snapshot.overview.resources }, { label: "Permission Denied（权限拒绝）", value: snapshot.overview.permissionDenials }, { label: "Quota Exceeded（配额拒绝）", value: snapshot.overview.quotaExceeded }, { label: "Audit Logs（审计记录）", value: snapshot.overview.auditLogs }] : []; // 第73天：整理治理总览六项核心指标卡片。
  return ( // 第73天：返回深色多租户生产治理仪表盘完整视图。
    <main className="h-full min-h-screen overflow-y-auto bg-[#07110f] text-slate-100"> {/* 第73天：定义可独立滚动的深色Governance Dashboard页面。 */}
      <div className="mx-auto w-full max-w-[1720px] p-4 sm:p-6"> {/* 第73天：定义响应式治理页面内容容器。 */}
        <header className="rounded-3xl border border-emerald-300/15 bg-[radial-gradient(circle_at_top_left,rgba(52,211,153,0.2),transparent_34%),linear-gradient(135deg,#10251f,#07110f_55%,#163c33)] p-5 shadow-2xl shadow-black/30"> {/* 第73天：定义智能体平台治理渐变标题区。 */}
          <div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-center gap-4"><div className="flex size-14 flex-col items-center justify-center rounded-2xl bg-emerald-300 text-slate-950"><span className="text-[9px] font-black uppercase">Day</span><span className="font-mono text-2xl font-black">73</span></div><div><p className="text-xs font-black uppercase tracking-[0.22em] text-emerald-200">Production Upgrade V10</p><h1 className="mt-1 text-2xl font-black sm:text-3xl">Agent Platform Governance & Production Readiness</h1><p className="mt-2 text-sm text-slate-400">智能体平台治理与生产就绪 · User → Tenant → RBAC → Quota → Audit</p></div></div><div className="flex flex-wrap gap-2"><button type="button" disabled={loading} onClick={() => void refresh()} className="rounded-xl border border-emerald-300/30 px-4 py-2 text-xs font-bold text-emerald-100 transition hover:bg-emerald-300/10 disabled:opacity-50">刷新Day73快照</button><Link href="/" className="rounded-xl border border-white/10 px-4 py-2 text-xs font-bold text-slate-300 transition hover:bg-white/5">返回Day73对话工作台</Link></div></div> {/* 第73天：展示Day73徽标、生产化升级标题、治理闭环和导航动作。 */}
          <div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{cards.map((card) => <article key={card.label} className="rounded-2xl border border-white/10 bg-slate-950/55 p-3"><p className="text-[11px] text-slate-500">{card.label}</p><p className="mt-2 font-mono text-xl font-black text-emerald-200">{card.value}</p></article>)}</div> {/* 第73天：展示租户、用户、资源、权限拒绝、配额拒绝和审计数量。 */}
        </header> {/* 第73天：结束智能体平台治理标题区。 */}
        {error ? <p className="mt-4 rounded-2xl border border-rose-300/20 bg-rose-300/10 p-4 text-sm text-rose-100">{error}</p> : null} {/* 第73天：按需展示治理平台请求错误。 */}
        <nav className="mt-4 grid gap-2 rounded-3xl border border-white/10 bg-slate-950/70 p-2 md:grid-cols-3 xl:grid-cols-6" role="tablist" aria-label="Day 73 Agent Platform Governance标签页">{TABS.map((tab) => <button key={tab.id} type="button" role="tab" aria-selected={activeTab === tab.id} onClick={() => setActiveTab(tab.id)} className={`rounded-2xl px-4 py-3 text-left transition ${activeTab === tab.id ? "bg-emerald-300 text-slate-950" : "text-slate-400 hover:bg-white/5 hover:text-white"}`}><span className="block text-sm font-black">{tab.label}</span><span className={`mt-1 block text-[11px] ${activeTab === tab.id ? "text-slate-700" : "text-slate-600"}`}>{tab.description}</span></button>)}</nav> {/* 第73天：渲染六个生产治理标签页。 */}
        {!snapshot ? <div className="mt-4 rounded-3xl border border-dashed border-emerald-300/25 py-24 text-center text-emerald-200">正在初始化Identity、Tenant、RBAC、Quota、API Gateway、Audit与Security Tests…</div> : null} {/* 第73天：快照未就绪时展示治理能力初始化占位。 */}
        {snapshot && activeTab === "overview" ? <section className="mt-4 grid gap-4 xl:grid-cols-[1.1fr_0.9fr]"><article className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><h2 className="text-lg font-black">Multi-Tenant Governance Flow（多租户治理链路）</h2><div className="mt-5 grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{["User 用户", "Tenant 租户", "Auth / RBAC", "RuntimeContext", "Agent Platform", "Audit / Governance"].map((item, index) => <div key={item} className="relative rounded-2xl border border-emerald-300/15 bg-emerald-300/5 p-4 text-center"><p className="text-[10px] text-emerald-300">STEP {index + 1}</p><p className="mt-2 text-xs font-black">{item}</p>{index < 5 ? <span className="absolute -right-3 top-1/2 hidden -translate-y-1/2 text-emerald-300 lg:block">→</span> : null}</div>)}</div><div className="mt-5 rounded-2xl border border-emerald-300/20 bg-emerald-300/10 p-4"><p className="text-xs font-black text-emerald-200">Agent Platform v1.0 Production Ready</p><p className="mt-2 text-sm text-slate-300">{snapshot.overview.productionReady ? "六类生产安全测试全部通过，平台达到生产就绪演示状态。" : "仍有生产安全测试未通过，请查看Security Tests。"}</p></div></article><article className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><h2 className="text-lg font-black">Production Security Test（生产安全测试）</h2><div className="mt-4 space-y-2">{snapshot.securityTests.map((test) => <div key={test.id} className={`rounded-2xl border p-3 ${test.passed ? "border-emerald-300/20 bg-emerald-300/5" : "border-rose-300/20 bg-rose-300/5"}`}><div className="flex items-center justify-between gap-3"><p className="text-xs font-black">{test.name}</p><span className={`rounded-full px-2 py-1 text-[9px] font-black ${test.passed ? "bg-emerald-300/15 text-emerald-200" : "bg-rose-300/15 text-rose-200"}`}>{test.passed ? "PASSED" : "FAILED"}</span></div><p className="mt-2 text-[11px] leading-5 text-slate-500">{test.evidence}</p></div>)}</div></article></section> : null} {/* 第73天：展示最终治理架构、生产就绪状态和六个安全场景。 */}
        {snapshot && activeTab === "tenants" ? <section className="mt-4 grid gap-4 xl:grid-cols-[0.32fr_0.68fr]"><aside className="space-y-2">{snapshot.tenants.map((tenant) => <button key={tenant.id} type="button" onClick={() => setSelectedTenantId(tenant.id)} className={`w-full rounded-2xl border p-4 text-left transition ${selectedTenant?.id === tenant.id ? "border-emerald-300/40 bg-emerald-300/10" : "border-white/10 bg-slate-950/70 hover:bg-white/[0.04]"}`}><div className="flex items-center justify-between gap-3"><h2 className="font-black">{tenant.name}</h2><span className="rounded-full bg-white/5 px-2 py-1 text-[9px] font-black uppercase text-emerald-200">{tenant.plan}</span></div><p className="mt-2 font-mono text-[10px] text-slate-600">{tenant.id}</p><p className="mt-2 text-[10px] text-slate-500">{tenant.status} · {formatTime(tenant.createdAt)}</p></button>)}</aside><div className="space-y-4"><article className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><h2 className="text-lg font-black">{selectedTenant?.name} · Users（用户）</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{selectedMemberships.map((membership) => { const user = snapshot.users.find((item) => item.id === membership.userId); return <div key={membership.id} className="rounded-2xl bg-white/[0.03] p-4"><p className="font-black text-emerald-100">{user?.name ?? membership.userId}</p><p className="mt-1 text-xs text-slate-500">{user?.email ?? "—"}</p><div className="mt-3 flex flex-wrap gap-1">{membership.roleIds.map((roleId) => <span key={roleId} className="rounded-full bg-emerald-300/10 px-2 py-1 text-[9px] text-emerald-200">{snapshot.roles.find((role) => role.id === roleId)?.name ?? roleId}</span>)}</div></div>; })}</div></article><article className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><h2 className="text-lg font-black">Resource Ownership（资源归属） · {selectedResources.length}</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{selectedResources.map((resource) => <div key={resource.id} className="rounded-2xl border border-white/5 bg-white/[0.02] p-4"><div className="flex items-center justify-between gap-2"><span className="text-[10px] font-black uppercase text-emerald-300">{resource.type}</span><span className="text-[10px] text-slate-600">{resource.size} units</span></div><h3 className="mt-2 font-black">{resource.name}</h3><p className="mt-2 font-mono text-[9px] text-slate-600">tenantId：{resource.ownerContext.tenantId}</p><p className="mt-1 font-mono text-[9px] text-slate-600">createdBy：{resource.ownerContext.createdBy}</p></div>)}</div></article></div></section> : null} {/* 第73天：展示租户、用户角色映射和资源所有者上下文。 */}
        {snapshot && activeTab === "permissions" ? <section className="mt-4 grid gap-4 xl:grid-cols-[0.6fr_0.4fr]"><article className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><h2 className="text-lg font-black">RBAC Roles & Permissions（角色与权限）</h2><div className="mt-4 grid gap-4 lg:grid-cols-2">{snapshot.roles.map((role) => <div key={role.id} className="rounded-2xl border border-white/5 bg-white/[0.02] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black text-emerald-300">{role.id}</p><h3 className="mt-1 text-lg font-black">{role.name}</h3></div><span className="rounded-full bg-emerald-300/10 px-2 py-1 text-[10px] text-emerald-200">{role.permissions.length} permissions</span></div><p className="mt-2 text-xs text-slate-500">{role.description}</p><div className="mt-3 flex flex-wrap gap-1">{role.permissions.map((permission) => <span key={permission} className="rounded-lg bg-black/20 px-2 py-1 font-mono text-[9px] text-slate-400">{permission}</span>)}</div></div>)}</div></article><article className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><h2 className="text-lg font-black">Permission Denied（权限拒绝）</h2><div className="mt-4 space-y-3">{snapshot.auditLogs.filter((log) => log.result === "permission_denied").map((log) => <div key={log.id} className="rounded-2xl border border-amber-300/20 bg-amber-300/5 p-4"><p className="font-mono text-xs font-black text-amber-200">{log.action}</p><p className="mt-2 text-xs text-slate-400">user：{log.userId}</p><p className="mt-1 text-xs text-slate-400">tenant：{log.tenantId}</p><p className="mt-2 text-[11px] leading-5 text-slate-500">{log.reason}</p></div>)}</div></article></section> : null} {/* 第73天：展示默认角色权限矩阵和权限拒绝证据。 */}
        {snapshot && activeTab === "audit" ? <section className="mt-4 rounded-3xl border border-white/10 bg-slate-950/70 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-black">Audit Log（审计日志） · {snapshot.auditLogs.length}</h2><span className="rounded-full bg-emerald-300/10 px-3 py-2 text-[10px] font-black text-emerald-200">SHA-256 Tamper Evidence（防篡改哈希链）</span></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[980px] text-left text-xs"><thead className="text-[10px] uppercase text-slate-600"><tr><th className="px-3 py-2">When</th><th className="px-3 py-2">Who / Tenant</th><th className="px-3 py-2">Action</th><th className="px-3 py-2">Resource</th><th className="px-3 py-2">Result</th><th className="px-3 py-2">Trace / Integrity</th></tr></thead><tbody>{snapshot.auditLogs.slice().reverse().map((log) => <tr key={log.id} className="border-t border-white/5"><td className="px-3 py-3 text-slate-500">{formatTime(log.timestamp)}</td><td className="px-3 py-3"><p className="text-slate-300">{log.userId}</p><p className="mt-1 font-mono text-[9px] text-slate-600">{log.tenantId}</p></td><td className="px-3 py-3 font-mono text-emerald-200">{log.action}</td><td className="px-3 py-3"><p>{log.resourceType}</p><p className="mt-1 font-mono text-[9px] text-slate-600">{log.resourceId}</p></td><td className="px-3 py-3"><span className={`rounded-full px-2 py-1 text-[9px] font-black ${resultClass(log.result)}`}>{log.result}</span><p className="mt-2 max-w-52 text-[10px] text-slate-600">{log.reason}</p></td><td className="px-3 py-3 font-mono text-[9px] text-slate-600"><p>{log.traceId}</p><p className="mt-1 truncate">hash：{log.integrityHash.slice(0, 18)}…</p></td></tr>)}</tbody></table></div></section> : null} {/* 第73天：展示谁在何时对何资源执行何动作、结果和防篡改哈希。 */}
        {snapshot && activeTab === "quota" ? <section className="mt-4 grid gap-4 xl:grid-cols-[0.35fr_0.65fr]"><aside className="space-y-2">{snapshot.quotas.map((item) => <button key={item.tenant.id} type="button" onClick={() => setSelectedTenantId(item.tenant.id)} className={`w-full rounded-2xl border p-4 text-left ${selectedTenant?.id === item.tenant.id ? "border-emerald-300/40 bg-emerald-300/10" : "border-white/10 bg-slate-950/70"}`}><div className="flex items-center justify-between gap-2"><p className="font-black">{item.tenant.name}</p><span className={`rounded-full px-2 py-1 text-[9px] font-black ${item.exceeded ? "bg-rose-300/10 text-rose-200" : "bg-emerald-300/10 text-emerald-200"}`}>{item.exceeded ? "LIMIT" : "HEALTHY"}</span></div><p className="mt-2 text-[10px] uppercase text-slate-600">{item.tenant.plan}</p></button>)}</aside><article className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><h2 className="text-lg font-black">{selectedTenant?.name} · Usage Quota（用量配额）</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{selectedQuota ? [{ label: "Daily Tokens（每日令牌）", current: selectedQuota.usage.dailyTokens, limit: selectedQuota.quota.dailyTokens }, { label: "Monthly Cost（月度成本）", current: selectedQuota.usage.monthlyCost, limit: selectedQuota.quota.monthlyCost }, { label: "Workflow Count（工作流数量）", current: selectedQuota.usage.workflowCount, limit: selectedQuota.quota.maxWorkflow }, { label: "Knowledge Size（知识容量）", current: selectedQuota.usage.knowledgeSize, limit: selectedQuota.quota.maxKnowledgeSize }].map((item) => <div key={item.label} className="rounded-2xl bg-white/[0.03] p-4"><div className="flex items-center justify-between gap-3"><p className="text-xs font-black">{item.label}</p><span className="font-mono text-xs text-emerald-200">{item.current} / {item.limit}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-black/30"><div className={`h-full rounded-full ${percent(item.current, item.limit) >= 100 ? "bg-rose-400" : percent(item.current, item.limit) >= 80 ? "bg-amber-300" : "bg-emerald-300"}`} style={{ width: `${percent(item.current, item.limit)}%` }} /></div><p className="mt-2 text-right font-mono text-[10px] text-slate-600">{percent(item.current, item.limit)}%</p></div>) : null}</div></article></section> : null} {/* 第73天：展示每个租户的令牌、成本、工作流和知识容量额度进度。 */}
        {snapshot && activeTab === "security" ? <section className="mt-4 grid gap-4 xl:grid-cols-2"><article className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><h2 className="text-lg font-black">API Gateway Layer（接口网关层）</h2><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{["Authentication 身份认证", "Authorization 权限授权", "Rate Limit 请求限流", "Request Context 请求上下文"].map((item, index) => <div key={item} className="rounded-2xl border border-emerald-300/15 bg-emerald-300/5 p-4"><p className="text-[10px] text-emerald-300">BOUNDARY {index + 1}</p><p className="mt-2 text-xs font-black">{item}</p></div>)}</div><p className="mt-4 rounded-2xl bg-black/20 p-4 font-mono text-xs text-emerald-200">POST /api/v1/governance</p><div className="mt-4"><p className="text-xs font-black">RuntimeContext Security Context</p><pre className="mt-2 max-h-52 overflow-auto whitespace-pre-wrap rounded-2xl bg-black/20 p-4 text-[10px] leading-5 text-slate-500">{JSON.stringify(snapshot.runtimeContexts.find((context) => context.securityContext)?.securityContext ?? {}, null, 2)}</pre></div></article><article className="rounded-3xl border border-white/10 bg-slate-950/70 p-5"><h2 className="text-lg font-black">EventBus / UnifiedRegistry / Trace</h2><div className="mt-4 space-y-4"><div className="rounded-2xl bg-white/[0.03] p-4"><p className="text-xs font-black text-amber-300">EventBus · {snapshot.events.length}</p><div className="mt-3 flex flex-wrap gap-1">{Array.from(new Set(snapshot.events.map((event) => event.type))).map((type) => <span key={type} className="rounded-full bg-black/20 px-2 py-1 font-mono text-[9px] text-slate-400">{type}</span>)}</div></div><div className="rounded-2xl bg-white/[0.03] p-4"><p className="text-xs font-black text-violet-300">UnifiedRegistry · {snapshot.registryItems.length}</p><ul className="mt-3 space-y-2 text-[11px] text-slate-500">{snapshot.registryItems.map((item) => <li key={item.id}><span className="font-mono text-violet-200">{item.id}</span> · {item.name} · {item.version}</li>)}</ul></div><div className="rounded-2xl bg-white/[0.03] p-4"><p className="text-xs font-black text-cyan-300">Distributed Trace · {snapshot.traces.length}</p><div className="mt-3 space-y-2">{snapshot.traces.map((trace) => <div key={trace.traceId} className="rounded-xl bg-black/20 p-3"><p className="text-xs font-black">{trace.rootOperation}</p><p className="mt-1 break-all font-mono text-[9px] text-slate-600">{trace.traceId} · {trace.status} · {trace.spans.length} spans</p></div>)}</div></div></div></article></section> : null} {/* 第73天：展示API网关四道边界、RuntimeContext、治理事件、注册能力和完整链路。 */}
      </div> {/* 第73天：结束响应式治理页面内容容器。 */}
    </main> // 第73天：结束深色智能体平台治理仪表盘页面。
  ); // 第73天：结束GovernanceDashboard视图返回。
} // 第73天：结束智能体平台治理仪表盘组件。
