import { API_REASON, apiJsonReasonError, apiJsonSuccess } from "@/lib/api/api-envelope"; // 第69天：引入统一 API 成功与错误响应封装。
import { productionKnowledgePlatform } from "@/lib/knowledge/production-knowledge-platform"; // 第69天：引入进程级生产知识平台单例处理治理动作。
import { KNOWLEDGE_SCOPES, type KnowledgeBaseStatus, type KnowledgeScope, type RetrievalStrategy } from "@/lib/knowledge/production-knowledge-types"; // 第69天：引入知识作用域、状态和检索策略类型用于请求校验。
type JsonBody = Record<string, unknown>; // 第69天：定义 Route Handler 接收的通用 JSON 对象类型。
function text(value: unknown): string { return typeof value === "string" ? value.trim() : ""; } // 第69天：把未知请求字段安全标准化为去首尾空白字符串。
function isScope(value: unknown): value is KnowledgeScope { return typeof value === "string" && KNOWLEDGE_SCOPES.includes(value as KnowledgeScope); } // 第69天：校验请求作用域是否属于生产知识平台允许值。
function isBaseStatus(value: unknown): value is KnowledgeBaseStatus { return typeof value === "string" && ["active", "disabled", "archived", "deleting"].includes(value); } // 第69天：校验知识库治理状态是否合法。
function isStrategy(value: unknown): value is RetrievalStrategy { return typeof value === "string" && ["fast", "balanced", "quality"].includes(value); } // 第69天：校验生产检索策略是否合法。
export async function GET(request: Request) { try { const seed = new URL(request.url).searchParams.get("seed") !== "false"; return apiJsonSuccess(await productionKnowledgePlatform.getSnapshot(seed), "production knowledge snapshot"); } catch (error) { return apiJsonReasonError(API_REASON.INTERNAL, error instanceof Error ? error.message : "Production Knowledge GET failed"); } } // 第69天：返回知识库、文档、索引、任务、检索、指标、事件和一致性完整快照。
export async function POST(request: Request) { try { const body = await request.json() as JsonBody; const action = text(body.action); if (action === "create_knowledge_base" && isScope(body.scope) && text(body.name) && text(body.scopeId)) return apiJsonSuccess(await productionKnowledgePlatform.createKnowledgeBase({ name: text(body.name), description: text(body.description) || undefined, scope: body.scope, scopeId: text(body.scopeId), createdBy: text(body.createdBy) || undefined }), "knowledge base created"); if (action === "upload_document" && text(body.knowledgeBaseId) && text(body.title) && text(body.content)) return apiJsonSuccess(await productionKnowledgePlatform.uploadDocument({ knowledgeBaseId: text(body.knowledgeBaseId), title: text(body.title), content: text(body.content), mimeType: text(body.mimeType) || undefined }), "knowledge document uploaded and queued"); if (action === "retrieve" && text(body.query)) return apiJsonSuccess(await productionKnowledgePlatform.retrieve({ query: text(body.query), accessContext: productionKnowledgePlatform.accessContext({ userId: text(body.userId) || undefined, workspaceId: text(body.workspaceId) || undefined, teamIds: Array.isArray(body.teamIds) ? body.teamIds.filter((item): item is string => typeof item === "string") : [], isAdmin: body.isAdmin === true }), knowledgeBaseIds: Array.isArray(body.knowledgeBaseIds) ? body.knowledgeBaseIds.filter((item): item is string => typeof item === "string") : undefined, strategy: isStrategy(body.strategy) ? body.strategy : "balanced", topK: typeof body.topK === "number" ? body.topK : 5, recallK: typeof body.recallK === "number" ? body.recallK : 12, minScore: typeof body.minScore === "number" ? body.minScore : 0.08, requireCitations: body.requireCitations !== false, allowGlobalKnowledge: body.allowGlobalKnowledge !== false }), "production retrieval completed"); return apiJsonReasonError(API_REASON.WORKFLOW_JSON_INVALID, "第69天 POST action 或参数不完整"); } catch (error) { return apiJsonReasonError(API_REASON.WORKFLOW_JSON_INVALID, error instanceof Error ? error.message : "Production Knowledge POST failed"); } } // 第69天：处理创建知识库、上传文档和生产检索第二版动作。
export async function PATCH(request: Request) { try { const body = await request.json() as JsonBody; const action = text(body.action); if (action === "process_next_job") return apiJsonSuccess(await productionKnowledgePlatform.processNextJob(), "next knowledge job processed"); if (action === "drain_jobs") return apiJsonSuccess(await productionKnowledgePlatform.drainJobs(), "all knowledge jobs processed"); if (action === "update_document" && text(body.documentId) && text(body.content)) return apiJsonSuccess(await productionKnowledgePlatform.updateDocument(text(body.documentId), { title: text(body.title) || undefined, content: text(body.content), mimeType: text(body.mimeType) || undefined }), "knowledge document update queued"); if (action === "rebuild_document" && text(body.documentId)) return apiJsonSuccess(await productionKnowledgePlatform.rebuildDocument(text(body.documentId)), "knowledge document rebuild queued"); if (action === "retry_failed_index" && text(body.documentId)) return apiJsonSuccess(await productionKnowledgePlatform.retryFailedIndex(text(body.documentId)), "failed index retried"); if (action === "delete_document" && text(body.documentId)) return apiJsonSuccess(await productionKnowledgePlatform.deleteDocument(text(body.documentId)), "knowledge document deleting"); if (action === "delete_knowledge_base" && text(body.knowledgeBaseId)) return apiJsonSuccess(await productionKnowledgePlatform.deleteKnowledgeBase(text(body.knowledgeBaseId)), "knowledge base deleting"); if (action === "set_knowledge_base_status" && text(body.knowledgeBaseId) && isBaseStatus(body.status)) return apiJsonSuccess(await productionKnowledgePlatform.setKnowledgeBaseStatus(text(body.knowledgeBaseId), body.status), "knowledge base status updated"); if (action === "scan_consistency") return apiJsonSuccess(await productionKnowledgePlatform.scanConsistency(body.autoRepairSafeItems === true), "knowledge consistency scanned"); return apiJsonReasonError(API_REASON.WORKFLOW_JSON_INVALID, "第69天 PATCH action 或参数不完整"); } catch (error) { return apiJsonReasonError(API_REASON.WORKFLOW_JSON_INVALID, error instanceof Error ? error.message : "Production Knowledge PATCH failed"); } } // 第69天：处理 Worker 驱动、更新、重建、重试、两阶段删除、知识库治理和一致性扫描动作。
